import type { Lang } from '../i18n'

// « Le défi du jour » — the shipped, offline-first deck of day-long family défis
// (« porte du jaune », « salue une nouvelle personne »). Each entry is bilingual
// and lightly tagged so a future picker (and the optional AI variant) can bias by
// venue / season, but the base pige is a plain no-repeat shuffle over the whole
// deck. Register is Québécois FR, and every line is written to be spoken aloud
// (TTS, the toddler tile).
//
// CALM (NFR-CALM-1): these are INVITATIONS, never quotas. Nothing here counts,
// ranks, or must be done. Drawing, accepting and checking off are all optional.

export type DefiVenue = 'in' | 'out' // undefined = either
export type DefiSeason = 'winter' | 'summer' | 'rain' // undefined = any time
export type DefiNeeds = 'clothes' | 'people' | 'supplies' // a small prerequisite

export interface Defi {
  fr: string
  en: string
  venue?: DefiVenue
  season?: DefiSeason
  needs?: DefiNeeds
}

// A no-repeat draw. `exclude` holds recently-drawn texts (normalized), so the
// household rarely sees the same défi twice running; `rng` is injectable so a test
// can pin the pick. Falls back to the full deck once everything has been seen.
export function pigeDefi(exclude: Set<string>, lang: Lang, rng: () => number = Math.random): Defi {
  const fresh = DEFI_DECK.filter((d) => !exclude.has(d[lang].trim().toLowerCase()))
  const pool = fresh.length ? fresh : DEFI_DECK
  return pool[Math.min(pool.length - 1, Math.floor(rng() * pool.length))]
}

// A committed défi is stored as plain text (one language, like a note/mot). For a
// DECK défi we can still show it in the reader's language: match the stored text
// against the deck (either language) and return the current-lang string. A custom
// or AI défi has no deck match → shown as typed. Lazy map, built once.
let byText: Map<string, Defi> | null = null
export function localizeDefi(text: string, lang: Lang): string {
  if (!byText) {
    byText = new Map()
    for (const d of DEFI_DECK) {
      byText.set(d.fr.trim().toLowerCase(), d)
      byText.set(d.en.trim().toLowerCase(), d)
    }
  }
  const hit = byText.get(text.trim().toLowerCase())
  return hit ? hit[lang] : text
}

export const DEFI_DECK: Defi[] = [
  // A · Couleur & thème du jour
  { fr: 'Porte du jaune aujourd’hui.', en: 'Wear something yellow today.', needs: 'clothes' },
  { fr: 'Porte du rouge aujourd’hui.', en: 'Wear something red today.', needs: 'clothes' },
  { fr: 'Porte du bleu de la tête aux pieds si tu peux.', en: 'Wear blue head to toe if you can.', needs: 'clothes' },
  { fr: 'Porte deux couleurs qui « ne vont pas ensemble », fièrement.', en: 'Wear two colours that “don’t match”, proudly.', needs: 'clothes' },
  { fr: 'Habille-toi dans les couleurs d’un fruit — fais deviner lequel au souper.', en: 'Dress in a fruit’s colours — make them guess which at supper.', needs: 'clothes' },
  { fr: 'Journée rayures : trouve au moins une rayure à porter.', en: 'Stripes day: find at least one striped thing to wear.', needs: 'clothes' },
  { fr: 'Journée pois ou motifs : le plus de motifs possible.', en: 'Polka-dots or patterns day: as many patterns as you can.', needs: 'clothes' },
  { fr: 'Porte la couleur préférée de quelqu’un d’autre de la famille.', en: 'Wear someone else in the family’s favourite colour.', needs: 'clothes' },
  { fr: 'Toute la famille tente la même couleur sans se consulter — vérification au souper.', en: 'The whole family tries the same colour without planning — check at supper.', needs: 'clothes' },
  { fr: 'Porte quelque chose de brillant ou qui scintille.', en: 'Wear something shiny or sparkly.', needs: 'clothes' },
  { fr: 'Journée camouflage : habille-toi pour te fondre dans le sofa (ou le salon).', en: 'Camouflage day: dress to blend into the couch (or the living room).', needs: 'clothes' },
  { fr: 'Porte les couleurs de la météo du jour.', en: 'Wear the colours of today’s weather.', needs: 'clothes' },
  { fr: 'Trouve trois choses à porter de la couleur de tes yeux.', en: 'Find three things to wear the colour of your eyes.', needs: 'clothes' },
  { fr: 'Journée arc-en-ciel : le plus de couleurs différentes sur toi.', en: 'Rainbow day: as many different colours on you as possible.', needs: 'clothes' },
  { fr: 'Porte du vert et repère tout ce qui est vert de la journée.', en: 'Wear green and spot everything green all day.', needs: 'clothes' },
  { fr: 'Habille-toi comme une saison qui n’est pas la bonne.', en: 'Dress for the wrong season on purpose.', needs: 'clothes' },
  { fr: 'Porte une couleur que tu ne portes jamais.', en: 'Wear a colour you never wear.', needs: 'clothes' },
  { fr: 'Choisis la couleur du jour pour toute la famille, ce matin.', en: 'Pick the family’s colour of the day, this morning.' },

  // B · Costume & style
  { fr: 'Porte deux bas différents, et assume toute la journée.', en: 'Wear two different socks, and own it all day.', needs: 'clothes' },
  { fr: 'Porte quelque chose à l’envers, discrètement ou pas.', en: 'Wear something backwards, subtly or not.', needs: 'clothes' },
  { fr: 'Journée chapeau : garde un chapeau le plus longtemps possible dans la maison.', en: 'Hat day: keep a hat on as long as you can indoors.', venue: 'in', needs: 'clothes' },
  { fr: 'Coiffure folle aujourd’hui — la gravité est ta seule limite.', en: 'Wild hair today — gravity is your only limit.' },
  { fr: 'Porte quelque chose qui appartient à quelqu’un d’autre (avec permission!).', en: 'Wear something that belongs to someone else (with permission!).', needs: 'clothes' },
  { fr: 'Journée jumeaux : habille-toi pareil comme quelqu’un de la famille.', en: 'Twins day: dress the same as someone in the family.', needs: 'clothes' },
  { fr: 'Porte quelque chose que tu n’as pas mis depuis un an.', en: 'Wear something you haven’t worn in a year.', needs: 'clothes' },
  { fr: 'Habille-toi comme le métier que tu rêvais de faire à cinq ans.', en: 'Dress as the job you dreamed of at five.', needs: 'clothes' },
  { fr: 'Journée pyjama assumée (si l’horaire le permet!).', en: 'Full pyjama day (schedule permitting!).', venue: 'in', needs: 'clothes' },
  { fr: 'Porte un accessoire inutile mais magnifique toute la journée.', en: 'Wear one useless but magnificent accessory all day.', needs: 'clothes' },
  { fr: 'Habille-toi comme un personnage de livre — on devine au souper.', en: 'Dress as a book character — we guess at supper.', needs: 'clothes' },
  { fr: 'Journée « trop chic pour rien » : habille-toi comme pour un gala.', en: '“Too fancy for no reason” day: dress like it’s a gala.', needs: 'clothes' },
  { fr: 'Porte tes vêtements les plus confortables et remarque la différence.', en: 'Wear your comfiest clothes and notice the difference.', needs: 'clothes' },
  { fr: 'Ajoute un détail secret à ta tenue — qui le remarquera?', en: 'Add a secret detail to your outfit — who’ll notice?', needs: 'clothes' },
  { fr: 'Habille-toi dans une seule décennie : années 80, 90, 2000…', en: 'Dress from a single decade: the 80s, 90s, 2000s…', needs: 'clothes' },
  { fr: 'Garde un petit trésor dans ta poche toute la journée; montre-le au souper.', en: 'Keep a little treasure in your pocket all day; show it at supper.' },
  { fr: 'Porte quelque chose de fait à la main.', en: 'Wear something handmade.', needs: 'clothes' },
  { fr: 'Journée lunettes rigolotes ou moustache dessinée (lavable!).', en: 'Funny glasses or a drawn-on moustache day (washable!).' },

  // C · Façon de parler
  { fr: 'Parle doucement toute la journée, comme un bibliothécaire.', en: 'Speak softly all day, like a librarian.' },
  { fr: 'Aujourd’hui on ne dit pas « non » — trouve une autre façon.', en: 'Today we don’t say “no” — find another way.' },
  { fr: 'Remplace « ok » par « excellente idée! » toute la journée.', en: 'Swap “ok” for “great idea!” all day.' },
  { fr: 'Appelle tout le monde « cher » ou « chère ».', en: 'Call everyone “dear” today.' },
  { fr: 'Chaque « merci » vient avec le pourquoi.', en: 'Every “thank you” comes with the reason why.' },
  { fr: 'Invente un mot ce matin et glisse-le dans trois conversations.', en: 'Invent a word this morning and slip it into three conversations.' },
  { fr: 'Pose une question avant de donner ton avis, toute la journée.', en: 'Ask a question before giving your opinion, all day.' },
  { fr: 'Dis « bonjour » dans une langue différente à chaque personne.', en: 'Say “hello” in a different language to each person.' },
  { fr: 'Pas de « je suis pas capable » — dis « pas encore ».', en: 'No “I can’t” — say “not yet”.' },
  { fr: 'Termine tes phrases du souper en chantonnant.', en: 'End your supper sentences by humming them.' },
  { fr: 'Aujourd’hui, on parle en rimes le plus souvent possible.', en: 'Today, speak in rhymes as often as you can.' },
  { fr: 'Utilise le prénom des gens quand tu leur parles, toute la journée.', en: 'Use people’s names when you talk to them, all day.' },
  { fr: 'Journée sans se plaindre — transforme chaque plainte en demande.', en: 'No-complaining day — turn each complaint into a request.' },
  { fr: 'Décris ta journée au souper sans utiliser le mot « chose ».', en: 'Describe your day at supper without using the word “thing”.' },
  { fr: 'Chuchote dans le corridor toute la journée, comme au musée.', en: 'Whisper in the hallway all day, like a museum.', venue: 'in' },
  { fr: 'Parle de toi à la troisième personne pendant une heure.', en: 'Talk about yourself in the third person for an hour.' },
  { fr: 'Aujourd’hui, chaque « oui » se dit avec enthousiasme.', en: 'Today, every “yes” is said with real enthusiasm.' },
  { fr: 'Trouve trois occasions de dire « bravo » sincèrement.', en: 'Find three chances to say “well done” and mean it.' },
  { fr: 'Journée voix de radio : annonce les repas comme à la radio.', en: 'Radio-voice day: announce meals like a radio host.' },
  { fr: 'Apprends un nouveau mot ce matin et utilise-le trois fois.', en: 'Learn a new word this morning and use it three times.' },

  // D · Salutations & monde extérieur
  { fr: 'Salue une nouvelle personne aujourd’hui.', en: 'Greet one new person today.', needs: 'people' },
  { fr: 'Fais un compliment à quelqu’un en dehors de la famille.', en: 'Compliment someone outside the family.', needs: 'people' },
  { fr: 'Souris au chauffeur d’autobus, au facteur ou au voisin.', en: 'Smile at the bus driver, the mail carrier or a neighbour.', needs: 'people' },
  { fr: 'Apprends le prénom de quelqu’un que tu croises souvent.', en: 'Learn the name of someone you often cross paths with.', needs: 'people' },
  { fr: 'Demande à quelqu’un comment il va — et écoute vraiment.', en: 'Ask someone how they’re doing — and really listen.', needs: 'people' },
  { fr: 'Dis bonjour en premier, toute la journée.', en: 'Say hello first, all day long.', needs: 'people' },
  { fr: 'Fais un signe de la main à une fenêtre ou une voiture qui passe.', en: 'Wave at a window or a passing car.', venue: 'out' },
  { fr: 'Remercie quelqu’un qui fait son travail (caissier, brigadier, chauffeur).', en: 'Thank someone doing their job (a cashier, a crossing guard, a driver).', needs: 'people' },
  { fr: 'Tiens la porte à trois personnes aujourd’hui.', en: 'Hold the door for three people today.', needs: 'people' },
  { fr: 'Laisse passer quelqu’un devant toi dans une file.', en: 'Let someone go ahead of you in a line.', needs: 'people' },
  { fr: 'Souhaite une bonne journée à un inconnu, pour vrai.', en: 'Wish a stranger a good day, and mean it.', needs: 'people' },
  { fr: 'Demande un conseil à quelqu’un aujourd’hui — les gens aiment aider.', en: 'Ask someone for advice today — people like helping.', needs: 'people' },
  { fr: 'Salue chaque chien que tu rencontres (et son humain).', en: 'Greet every dog you meet (and its human).', venue: 'out' },
  { fr: 'Présente-toi à un voisin que tu ne connais pas encore.', en: 'Introduce yourself to a neighbour you don’t know yet.', needs: 'people' },
  { fr: 'Écris un petit mot gentil pour le facteur ou l’éboueur.', en: 'Write a kind note for the mail carrier or the garbage crew.' },
  { fr: 'Complimente le jardin, le balcon ou la déco de quelqu’un du quartier.', en: 'Compliment someone’s garden, balcony or decor in the neighbourhood.', venue: 'out' },
  { fr: 'Demande à quelqu’un la meilleure partie de sa journée.', en: 'Ask someone the best part of their day.', needs: 'people' },
  { fr: 'Fais rire quelqu’un en dehors de la maison aujourd’hui.', en: 'Make someone outside the house laugh today.', needs: 'people' },

  // E · Gentillesse dans la famille
  { fr: 'Sois l’aide secrète de quelqu’un toute la journée — sans te faire repérer.', en: 'Be someone’s secret helper all day — without getting caught.' },
  { fr: 'Laisse trois petits mots doux dans la maison.', en: 'Leave three little kind notes around the house.', venue: 'in' },
  { fr: 'Remercie chaque personne en la nommant par son prénom.', en: 'Thank each person by their first name.' },
  { fr: 'Chaque fois que quelqu’un aide, dis-le tout haut.', en: 'Every time someone helps, say it out loud.' },
  { fr: 'Rends deux services avant qu’on te les demande.', en: 'Do two favours before anyone asks.' },
  { fr: 'Laisse passer les autres en premier, partout, toute la journée.', en: 'Let others go first, everywhere, all day.' },
  { fr: 'Trouve une qualité à chaque membre de la famille; dis-les au souper.', en: 'Find a good quality in each family member; share them at supper.' },
  { fr: 'Fais durer un câlin trois secondes de plus que d’habitude.', en: 'Make a hug last three seconds longer than usual.' },
  { fr: 'Range quelque chose qui n’est pas à toi, sans le dire.', en: 'Tidy something that isn’t yours, without saying so.', venue: 'in' },
  { fr: 'Prépare la place de quelqu’un d’autre avant la tienne.', en: 'Set someone else’s spot before your own.', venue: 'in' },
  { fr: 'Fais le lit de quelqu’un d’autre en cachette.', en: 'Secretly make someone else’s bed.', venue: 'in' },
  { fr: 'Dessine un petit soleil et cache-le dans le sac ou la boîte à lunch de quelqu’un.', en: 'Draw a little sun and hide it in someone’s bag or lunchbox.' },
  { fr: 'Propose ton dessert à quelqu’un (il peut refuser!).', en: 'Offer your dessert to someone (they can say no!).' },
  { fr: 'Demande à chacun sa plus belle chose de la journée, avant le dodo.', en: 'Ask everyone the best thing about their day, before bed.' },
  { fr: 'Dis « je t’aime » à chaque personne de la maison aujourd’hui.', en: 'Say “I love you” to each person at home today.' },
  { fr: 'Écoute quelqu’un raconter quelque chose sans regarder ailleurs.', en: 'Listen to someone tell a story without looking away.' },
  { fr: 'Cède la meilleure place du sofa toute la soirée.', en: 'Give up the best couch spot all evening.', venue: 'in' },
  { fr: 'Fais une surprise de moins de deux minutes à quelqu’un.', en: 'Surprise someone with something under two minutes.' },

  // F · Gentillesse vers le monde
  { fr: 'Envoie un bonjour à un grand-parent aujourd’hui.', en: 'Send a hello to a grandparent today.' },
  { fr: 'Appelle quelqu’un juste pour dire que tu penses à lui.', en: 'Call someone just to say you’re thinking of them.' },
  { fr: 'Envoie une photo drôle à quelqu’un qui en a besoin.', en: 'Send a funny photo to someone who needs one.' },
  { fr: 'Écris une vraie carte postale (ou un dessin) à poster.', en: 'Write a real postcard (or a drawing) to mail.' },
  { fr: 'Mets de côté un jouet ou un vêtement à donner.', en: 'Set aside a toy or a piece of clothing to give away.', venue: 'in' },
  { fr: 'Mets une pièce dans un parcomètre ou un panier d’épicerie pour le suivant.', en: 'Leave a coin in a meter or a shopping cart for the next person.', venue: 'out' },
  { fr: 'Peins ou dessine une petite roche-surprise et laisse-la dans le parc.', en: 'Paint or draw a little surprise rock and leave it in the park.', venue: 'out' },
  { fr: 'Écris un message d’encouragement à la craie sur le trottoir.', en: 'Chalk an encouraging message on the sidewalk.', venue: 'out', season: 'summer' },
  { fr: 'Remercie un professeur, un entraîneur ou un moniteur aujourd’hui.', en: 'Thank a teacher, a coach or an instructor today.', needs: 'people' },
  { fr: 'Laisse une bonne évaluation à un petit commerce que tu aimes.', en: 'Leave a kind review for a small shop you love.' },
  { fr: 'Rapporte le bac ou la poubelle d’un voisin.', en: 'Bring in a neighbour’s bin or recycling.', venue: 'out' },
  { fr: 'Nourris les oiseaux aujourd’hui.', en: 'Feed the birds today.', venue: 'out', season: 'winter' },
  { fr: 'Ramasse trois déchets qui ne sont pas les tiens.', en: 'Pick up three pieces of litter that aren’t yours.', venue: 'out' },
  { fr: 'Dis à quelqu’un pourquoi il compte pour toi — pas juste « merci ».', en: 'Tell someone why they matter to you — not just “thanks”.' },
  { fr: 'Partage une collation avec quelqu’un aujourd’hui.', en: 'Share a snack with someone today.' },
  { fr: 'Souhaite la bienvenue à quelqu’un de nouveau (école, travail, quartier).', en: 'Welcome someone new (at school, work, the neighbourhood).', needs: 'people' },

  // G · Missions d'observation — dehors
  { fr: 'Repère un oiseau spécial aujourd’hui — décris-le au souper.', en: 'Spot a special bird today — describe it at supper.', venue: 'out' },
  { fr: 'Compte les chiens que tu vois aujourd’hui; le chiffre au souper!', en: 'Count the dogs you see today; share the number at supper!', venue: 'out' },
  { fr: 'Trouve la lettre de ton prénom cachée dans le monde (enseigne, branche, fissure…).', en: 'Find your name’s first letter hidden in the world (a sign, a branch, a crack…).', venue: 'out' },
  { fr: 'Repère trois choses jaunes que tu n’avais jamais remarquées.', en: 'Spot three yellow things you’d never noticed.', venue: 'out' },
  { fr: 'Trouve le plus beau nuage de la journée.', en: 'Find the best cloud of the day.', venue: 'out' },
  { fr: 'Remarque une chose nouvelle sur ton trajet habituel.', en: 'Notice one new thing on your usual route.', venue: 'out' },
  { fr: 'Cherche un cœur caché (roche, feuille, tache, nuage…).', en: 'Look for a hidden heart (a rock, a leaf, a stain, a cloud…).', venue: 'out' },
  { fr: 'Trouve le chiffre 7 trois fois aujourd’hui.', en: 'Find the number 7 three times today.' },
  { fr: 'Repère une voiture de ta couleur préférée — et une jaune.', en: 'Spot a car in your favourite colour — and a yellow one.', venue: 'out' },
  { fr: 'Trouve quelque chose de plus vieux que grand-papa.', en: 'Find something older than grandpa.' },
  { fr: 'Repère un écureuil qui travaille fort.', en: 'Spot a squirrel hard at work.', venue: 'out' },
  { fr: 'Trouve une maison devant laquelle tu n’es jamais passé.', en: 'Find a house you’ve never walked past before.', venue: 'out' },
  { fr: 'Cherche quelque chose de rond, de pointu et de rayé dehors.', en: 'Find something round, something pointy and something striped outside.', venue: 'out' },
  { fr: 'Repère le plus grand arbre de ta journée.', en: 'Spot the tallest tree of your day.', venue: 'out' },
  { fr: 'Trouve des traces d’animal (pattes, plumes, trous…).', en: 'Find animal traces (paw prints, feathers, holes…).', venue: 'out', season: 'winter' },
  { fr: 'Repère quelque chose qui pousse dans une fissure.', en: 'Spot something growing in a crack.', venue: 'out', season: 'summer' },
  { fr: 'Trouve trois sortes de feuilles différentes.', en: 'Find three different kinds of leaves.', venue: 'out' },
  { fr: 'Regarde le ciel trois fois aujourd’hui; note ce qui a changé.', en: 'Look at the sky three times today; notice what changed.', venue: 'out' },
  { fr: 'Cherche la première fleur, le premier bourgeon ou la première neige de la saison.', en: 'Look for the season’s first flower, first bud or first snow.', venue: 'out' },
  { fr: 'Repère un insecte au travail et regarde-le trente secondes.', en: 'Spot an insect at work and watch it for thirty seconds.', venue: 'out', season: 'summer' },
  { fr: 'Trouve quelque chose que le vent a déplacé.', en: 'Find something the wind moved.', venue: 'out' },
  { fr: 'Repère une flaque, un glaçon ou un ruisseau et écoute-le.', en: 'Find a puddle, an icicle or a stream and listen to it.', venue: 'out' },

  // H · Missions d'observation — partout
  { fr: 'Repère quelqu’un qui rit aux éclats aujourd’hui.', en: 'Spot someone laughing out loud today.' },
  { fr: 'Trouve trois choses qui fonctionnent à piles dans ta journée.', en: 'Find three things that run on batteries in your day.' },
  { fr: 'Remarque la plus belle porte que tu croises.', en: 'Notice the most beautiful door you pass.' },
  { fr: 'Trouve un objet plus vieux que toi dans la maison.', en: 'Find something older than you in the house.', venue: 'in' },
  { fr: 'Repère trois triangles dans ta journée.', en: 'Spot three triangles in your day.' },
  { fr: 'Trouve quelque chose qui brille sans être une lumière.', en: 'Find something that shines without being a light.' },
  { fr: 'Remarque ce que portent les gens aujourd’hui — c’est quoi la mode?', en: 'Notice what people are wearing today — what’s the trend?' },
  { fr: 'Trouve le mot le plus drôle écrit quelque part aujourd’hui.', en: 'Find the funniest word written somewhere today.' },
  { fr: 'Repère une horloge arrêtée ou une heure rigolote (11 h 11!).', en: 'Spot a stopped clock or a funny time (11:11!).' },
  { fr: 'Trouve cinq objets ronds dans une seule pièce.', en: 'Find five round objects in a single room.', venue: 'in' },
  { fr: 'Remarque la chose la plus douce que tu touches aujourd’hui.', en: 'Notice the softest thing you touch today.' },
  { fr: 'Trouve quelque chose d’exactement la couleur de tes yeux.', en: 'Find something exactly the colour of your eyes.' },
  { fr: 'Repère un chiffre qui est ton âge quelque part.', en: 'Spot a number that’s your age somewhere.' },
  { fr: 'Remarque une odeur que tu aimes et nomme-la.', en: 'Notice a smell you like and name it.' },
  { fr: 'Trouve la plus petite chose mignonne de ta journée.', en: 'Find the tiniest cute thing of your day.' },
  { fr: 'Repère quelque chose que tu vois tous les jours sans jamais le regarder.', en: 'Spot something you see every day but never really look at.' },

  // I · Chasse aux sons, textures & odeurs
  { fr: 'Trouve le plus beau son de ta journée.', en: 'Find the best sound of your day.' },
  { fr: 'Reste silencieux une minute et compte les sons que tu entends.', en: 'Stay silent one minute and count the sounds you hear.' },
  { fr: 'Trouve quelque chose de bosselé, de lisse et de piquant.', en: 'Find something bumpy, something smooth and something spiky.' },
  { fr: 'Écoute la pluie, le vent ou la neige une vraie minute.', en: 'Listen to the rain, wind or snow for a full minute.', season: 'winter' },
  { fr: 'Trouve trois objets qui font de la musique sans être des instruments.', en: 'Find three objects that make music without being instruments.', venue: 'in' },
  { fr: 'Repère un son que tu n’avais jamais remarqué chez toi.', en: 'Spot a sound at home you’d never noticed.', venue: 'in' },
  { fr: 'Sens trois choses de la cuisine les yeux fermés et devine.', en: 'Smell three kitchen things with your eyes closed and guess.', venue: 'in' },
  { fr: 'Écoute un oiseau jusqu’à ce qu’il se taise.', en: 'Listen to a bird until it goes quiet.', venue: 'out' },
  { fr: 'Trouve le coin le plus silencieux de la maison.', en: 'Find the quietest corner of the house.', venue: 'in' },
  { fr: 'Marche dix pas les yeux fermés (avec un guide!) et raconte ce que tu as senti.', en: 'Walk ten steps with eyes closed (with a guide!) and tell what you felt.' },
  { fr: 'Trouve quelque chose de froid, de tiède et de chaud (sécuritaire!).', en: 'Find something cold, something warm and something hot (safely!).' },
  { fr: 'Écoute une chanson entière sans rien faire d’autre.', en: 'Listen to a whole song doing nothing else.' },
  { fr: 'Devine qui marche dans le corridor sans regarder.', en: 'Guess who’s walking down the hall without looking.', venue: 'in' },
  { fr: 'Trouve le tissu le plus doux de la maison.', en: 'Find the softest fabric in the house.', venue: 'in' },

  // J · Règles de déplacement
  { fr: 'Ouvre toutes les portes avec ta main non-dominante.', en: 'Open every door with your non-dominant hand.' },
  { fr: 'Prends les escaliers chaque fois que tu as le choix.', en: 'Take the stairs whenever you have the choice.' },
  { fr: 'Marche par le chemin le plus long au moins une fois.', en: 'Take the long way at least once today.' },
  { fr: 'Saute par-dessus chaque seuil de porte aujourd’hui.', en: 'Jump over every doorway threshold today.' },
  { fr: 'Marche sur la pointe des pieds dans une pièce choisie, toute la journée.', en: 'Tiptoe through one chosen room, all day.', venue: 'in' },
  { fr: 'Le plancher du salon est de la lave, toute la journée.', en: 'The living room floor is lava, all day.', venue: 'in' },
  { fr: 'Monte l’escalier deux marches à la fois (ou une, très lentement).', en: 'Climb the stairs two steps at a time (or one, very slowly).' },
  { fr: 'Chaque fois que tu entres dans la cuisine, fais un petit pas de danse.', en: 'Every time you enter the kitchen, do a little dance step.', venue: 'in' },
  { fr: 'Assieds-toi à une place différente à chaque repas.', en: 'Sit in a different spot at each meal.', venue: 'in' },
  { fr: 'Traverse une pièce sans toucher le plancher, une fois.', en: 'Cross a room without touching the floor, once.', venue: 'in' },
  { fr: 'Marche une fois sans te presser du tout, exprès.', en: 'Walk once without rushing at all, on purpose.' },
  { fr: 'Prends un chemin que tu n’as jamais pris pour aller à un endroit connu.', en: 'Take a route you’ve never taken to a familiar place.', venue: 'out' },
  { fr: 'Tourne toujours à gauche en premier aujourd’hui (quand c’est possible!).', en: 'Always turn left first today (when you can!).' },
  { fr: 'Fais dix pas de géant et dix pas de souris quelque part.', en: 'Take ten giant steps and ten mouse steps somewhere.' },
  { fr: 'Recule de trois pas avant d’entrer dans ta chambre, à chaque fois.', en: 'Step back three paces before entering your room, every time.', venue: 'in' },
  { fr: 'Chaque déplacement dans le corridor se fait en mission secrète, sans bruit.', en: 'Every trip down the hall is a silent secret mission.', venue: 'in' },

  // K · Règles de repas
  { fr: 'Goûte quelque chose de vert à chaque repas.', en: 'Taste something green at every meal.' },
  { fr: 'Mange ta première bouchée de chaque repas les yeux fermés.', en: 'Eat the first bite of each meal with your eyes closed.' },
  { fr: 'Aujourd’hui, l’eau est ta seule boisson (les grands aussi!).', en: 'Today, water is your only drink (grown-ups too!).' },
  { fr: 'Décris chaque repas comme un juge de concours culinaire.', en: 'Describe each meal like a cooking-contest judge.' },
  { fr: 'Mange un fruit que tu n’as pas mangé ce mois-ci.', en: 'Eat a fruit you haven’t had this month.' },
  { fr: 'Remercie le cuisinier en nommant ton moment préféré du repas.', en: 'Thank the cook by naming your favourite part of the meal.' },
  { fr: 'Croque quelque chose de croquant à chaque repas et écoute.', en: 'Crunch something crunchy at each meal and listen.' },
  { fr: 'Le dessert se mange en trois petites bouchées minimum.', en: 'Dessert is eaten in at least three little bites.' },
  { fr: 'Devine une épice du souper sans demander.', en: 'Guess one spice in supper without asking.', venue: 'in' },
  { fr: 'Compose ton assiette avec au moins trois couleurs.', en: 'Build your plate with at least three colours.' },
  { fr: 'Mange une collation avec la mauvaise main.', en: 'Eat a snack with your wrong hand.' },
  { fr: 'Bois un verre d’eau avant chaque repas.', en: 'Drink a glass of water before each meal.' },
  { fr: 'Pas de coude sur la table — souper de château!', en: 'No elbows on the table — castle supper!', venue: 'in' },
  { fr: 'Donne un nom de restaurant au souper de ce soir et annonce le menu.', en: 'Give tonight’s supper a restaurant name and announce the menu.', venue: 'in' },
  { fr: 'Mange dehors ou pique-nique par terre au salon.', en: 'Eat outside, or picnic on the living-room floor.', season: 'summer' },
  { fr: 'La famille mange en silence les deux premières minutes — écoutez le repas.', en: 'The family eats in silence for the first two minutes — listen to the meal.', venue: 'in' },
  { fr: 'Chacun raconte le meilleur repas de sa vie, au souper.', en: 'Everyone tells the best meal of their life, at supper.', venue: 'in' },
  { fr: 'Mets la table comme dans un restaurant chic, avec serviettes pliées.', en: 'Set the table like a fancy restaurant, with folded napkins.', venue: 'in' },
  { fr: 'Goûte une bouchée du repas de quelqu’un d’autre (avec permission!).', en: 'Taste a bite of someone else’s meal (with permission!).' },
  { fr: 'Termine ton assiette avant de parler de dessert.', en: 'Finish your plate before talking about dessert.' },

  // L · Corps & posture
  { fr: 'Étire-toi vers le plafond chaque fois que tu bâilles.', en: 'Stretch to the ceiling every time you yawn.' },
  { fr: 'Marche aujourd’hui comme quelqu’un de très heureux.', en: 'Walk today like someone very happy.' },
  { fr: 'Tiens-toi droit comme un roi ou une reine toute la journée.', en: 'Stand tall like a king or queen all day.' },
  { fr: 'Danse dix secondes chaque fois qu’une chanson joue.', en: 'Dance ten seconds every time a song plays.' },
  { fr: 'Fais trois grandes respirations chaque fois que tu regardes dehors.', en: 'Take three big breaths each time you look outside.' },
  { fr: 'Chaque fois que tu t’assois, fais-le le plus lentement du monde.', en: 'Every time you sit down, do it as slowly as possible.' },
  { fr: 'Salue le matin par un grand étirement de chat.', en: 'Greet the morning with a big cat stretch.' },
  { fr: 'Trouve trois occasions de courir dehors.', en: 'Find three chances to run outside.', venue: 'out' },
  { fr: 'Tiens-toi sur un pied en te brossant les dents.', en: 'Stand on one foot while brushing your teeth.', venue: 'in' },
  { fr: 'Fais cinq sauts d’étoile avant chaque repas.', en: 'Do five star jumps before each meal.' },
  { fr: 'Marche comme un pingouin pour aller au bain, toute la journée.', en: 'Waddle like a penguin to the bath, all day.', venue: 'in' },
  { fr: 'Étire-toi jusqu’aux orteils au réveil et avant le dodo.', en: 'Stretch down to your toes at wake-up and before bed.' },
  { fr: 'Chaque cadre de porte = une petite flexion de genoux aujourd’hui.', en: 'Every doorframe = one little knee-bend today.' },
  { fr: 'Porte quelque chose sur ta tête d’une pièce à l’autre, une fois.', en: 'Carry something on your head from room to room, once.', venue: 'in' },
  { fr: 'Danse en te lavant les mains (toute la durée du savonnage!).', en: 'Dance while washing your hands (the whole soaping!).', venue: 'in' },
  { fr: 'Le ralenti est obligatoire dans le corridor, toute la soirée.', en: 'Slow motion is mandatory in the hallway, all evening.', venue: 'in' },

  // M · Mini-quêtes utiles
  { fr: 'Débarrasse-toi d’UNE chose aujourd’hui (donner, recycler, jeter).', en: 'Let go of ONE thing today (give, recycle, toss).', venue: 'in' },
  { fr: 'Répare ou recolle une petite chose qui traîne depuis longtemps.', en: 'Fix or re-glue one little thing that’s been waiting forever.', venue: 'in' },
  { fr: 'Range une chose chaque fois que tu changes de pièce.', en: 'Put one thing away each time you change rooms.', venue: 'in' },
  { fr: 'Vide UNE pochette, UN tiroir ou UNE tablette (juste une!).', en: 'Empty ONE pouch, ONE drawer or ONE shelf (just one!).', venue: 'in' },
  { fr: 'Redonne sa place à tout ce que tu utilises, toute la journée.', en: 'Put everything you use back in its place, all day.', venue: 'in' },
  { fr: 'Arrose les plantes en leur disant quelque chose de gentil.', en: 'Water the plants while telling them something kind.', venue: 'in' },
  { fr: 'Nettoie tes lunettes, ton écran ou une fenêtre — redécouvre le monde.', en: 'Clean your glasses, your screen or a window — see the world fresh.' },
  { fr: 'Recharge un appareil AVANT qu’il soit à plat, pour une fois.', en: 'Charge a device BEFORE it dies, for once.' },
  { fr: 'Prépare tes choses de demain, ce soir.', en: 'Get tomorrow’s things ready tonight.' },
  { fr: 'Trouve une chose que tu cherchais depuis des semaines.', en: 'Find something you’ve been looking for for weeks.', venue: 'in' },
  { fr: 'Fais briller UNE poignée de porte ou UN robinet.', en: 'Make ONE door handle or ONE faucet shine.', venue: 'in' },
  { fr: 'Adopte un objet perdu de la maison et trouve-lui une vraie place.', en: 'Adopt a lost object in the house and find it a real home.', venue: 'in' },
  { fr: 'Plie le linge en le triant par couleur, pour le plaisir.', en: 'Fold the laundry sorted by colour, for fun.', venue: 'in' },
  { fr: 'Mets de l’ordre dans UNE pile de papiers (juste une!).', en: 'Tidy ONE pile of papers (just one!).', venue: 'in' },
  { fr: 'Note une chose à réparer et dis-le à voix haute au souper.', en: 'Note one thing to fix and say it out loud at supper.' },
  { fr: 'Fais ton lit comme à l’hôtel, avec un pli parfait.', en: 'Make your bed like a hotel, with a perfect fold.', venue: 'in' },

  // N · Photo & dessin missions
  { fr: 'Prends en photo la plus belle lumière de ta journée.', en: 'Photograph the best light of your day.' },
  { fr: 'Dessine ta famille en animaux; on devine qui est qui.', en: 'Draw your family as animals; we guess who’s who.' },
  { fr: 'Photographie quelque chose de minuscule de très proche.', en: 'Photograph something tiny from very close.' },
  { fr: 'Dessine ce que tu vois par une fenêtre, en une minute.', en: 'Draw what you see through a window, in one minute.', venue: 'in' },
  { fr: 'Prends une photo de chaque couleur de l’arc-en-ciel aujourd’hui.', en: 'Take a photo of each rainbow colour today.' },
  { fr: 'Dessine ton souper avant de le manger.', en: 'Draw your supper before eating it.', venue: 'in' },
  { fr: 'Photographie quelque chose qui ressemble à un visage.', en: 'Photograph something that looks like a face.' },
  { fr: 'Dessine les yeux fermés et fais deviner ce que c’est.', en: 'Draw with your eyes closed and make them guess what it is.' },
  { fr: 'Prends une photo de famille rigolote avec le retardateur.', en: 'Take a silly family photo with the timer.', venue: 'in' },
  { fr: 'Dessine le portrait de quelqu’un en le regardant, sans regarder ta feuille.', en: 'Draw someone’s portrait looking at them, not your paper.' },
  { fr: 'Photographie la chose la plus vieille que tu croises.', en: 'Photograph the oldest thing you come across.' },
  { fr: 'Fais un dessin pour le frigo — thème : notre maison.', en: 'Make a fridge drawing — theme: our home.', venue: 'in' },
  { fr: 'Photographie ton coin préféré de la maison.', en: 'Photograph your favourite corner of the house.', venue: 'in' },
  { fr: 'Dessine la météo d’aujourd’hui comme une personne.', en: 'Draw today’s weather as a person.' },
  { fr: 'Prends une photo d’une ombre intéressante.', en: 'Take a photo of an interesting shadow.', season: 'summer' },
  { fr: 'Dessine ton défi d’hier de mémoire.', en: 'Draw yesterday’s challenge from memory.' },

  // O · Apprendre en un jour
  { fr: 'Apprends à dire « bonjour » dans une nouvelle langue.', en: 'Learn to say “hello” in a new language.' },
  { fr: 'Apprends un mot nouveau et utilise-le au souper.', en: 'Learn a new word and use it at supper.' },
  { fr: 'Compte jusqu’à dix dans une autre langue.', en: 'Count to ten in another language.' },
  { fr: 'Apprends à faire un nouveau nœud.', en: 'Learn to tie a new knot.' },
  { fr: 'Trouve c’est quoi le plus gros animal du monde.', en: 'Find out what the biggest animal in the world is.' },
  { fr: 'Trouve ton pays sur une carte, puis un pays tout petit.', en: 'Find your country on a map, then a very small one.' },
  { fr: 'Apprends un tour de magie simple et montre-le ce soir.', en: 'Learn a simple magic trick and show it tonight.' },
  { fr: 'Apprends trois signes de la langue des signes.', en: 'Learn three signs in sign language.' },
  { fr: 'Trouve pourquoi le ciel est bleu et explique-le au souper.', en: 'Find out why the sky is blue and explain it at supper.' },
  { fr: 'Apprends à plier un avion en papier qui vole VRAIMENT loin.', en: 'Learn to fold a paper plane that flies REALLY far.' },
  { fr: 'Apprends une devinette et pose-la à tout le monde.', en: 'Learn a riddle and ask everyone.' },
  { fr: 'Trouve le nom de trois oiseaux de ton quartier.', en: 'Find the names of three birds in your neighbourhood.', venue: 'out' },
  { fr: 'Apprends à écrire ton prénom dans un autre alphabet.', en: 'Learn to write your name in another alphabet.' },
  { fr: 'Trouve la capitale d’un pays que tu ne connais pas.', en: 'Find the capital of a country you don’t know.' },
  { fr: 'Apprends un pas de danse (vidéo permise!) et enseigne-le.', en: 'Learn a dance step (video allowed!) and teach it.' },
  { fr: 'Trouve d’où vient ton fruit préféré.', en: 'Find out where your favourite fruit comes from.' },
  { fr: 'Apprends à siffler avec tes doigts (ou continue d’essayer!).', en: 'Learn to whistle with your fingers (or keep trying!).' },
  { fr: 'Demande à un parent de te montrer une chose qu’il sait faire.', en: 'Ask a parent to show you something they know how to do.' },
  { fr: 'Apprends par cœur un tout petit poème ou une comptine.', en: 'Memorize a tiny poem or nursery rhyme.' },
  { fr: 'Trouve comment on dit « chat » dans cinq langues.', en: 'Find out how to say “cat” in five languages.' },

  // P · Gratitude & attention
  { fr: 'Note (ou dis) trois belles choses de ta journée avant de dormir.', en: 'Note (or say) three good things about your day before sleep.' },
  { fr: 'Remarque le moment le plus calme de ta journée; raconte-le ce soir.', en: 'Notice the calmest moment of your day; tell it tonight.' },
  { fr: 'Chaque attente (autobus, eau qui bout) devient trois grandes respirations.', en: 'Every wait (the bus, boiling water) becomes three big breaths.' },
  { fr: 'Écoute quelqu’un sans l’interrompre, du début à la fin.', en: 'Listen to someone without interrupting, start to finish.' },
  { fr: 'Trouve cinq minutes pour ne rien faire du tout. Rien!', en: 'Find five minutes to do absolutely nothing. Nothing!' },
  { fr: 'Remarque une chose qui pousse et surveille-la toute la journée.', en: 'Notice one thing that’s growing and keep an eye on it all day.' },
  { fr: 'Une heure sans écran, au moment de ton choix.', en: 'One screen-free hour, whenever you choose.' },
  { fr: 'Regarde une photo qui te rend heureux et raconte pourquoi.', en: 'Look at a photo that makes you happy and tell why.' },
  { fr: 'Dis merci pour une chose d’il y a longtemps.', en: 'Say thanks for something from long ago.' },
  { fr: 'Remarque qui t’a aidé aujourd’hui, même un tout petit peu.', en: 'Notice who helped you today, even a tiny bit.' },
  { fr: 'Trouve une chose que tu aimes de chaque saison.', en: 'Find one thing you love about each season.' },
  { fr: 'Avant chaque repas, une seconde de silence pour sentir.', en: 'Before each meal, one second of silence to smell it.' },
  { fr: 'Remercie ton corps pour une chose qu’il a faite aujourd’hui.', en: 'Thank your body for one thing it did today.' },
  { fr: 'Trouve quelque chose de gratuit qui t’a fait plaisir aujourd’hui.', en: 'Find one free thing that made you happy today.' },
  { fr: 'Regarde le coucher (ou lever) du soleil, au complet.', en: 'Watch the sunset (or sunrise), all the way through.', venue: 'out' },
  { fr: 'Pense à quelqu’un qui est loin et envoie-lui une pensée (ou un message).', en: 'Think of someone far away and send them a thought (or a message).' },
  { fr: 'Remarque trois choses que tu tiens pour acquises.', en: 'Notice three things you take for granted.' },
  { fr: 'Choisis ta plus belle minute de la journée et rejoue-la dans ta tête.', en: 'Pick your best minute of the day and replay it in your head.' },

  // Q · Espion & rôle secret
  { fr: 'Tu es un agent secret : accomplis tes tâches sans te faire repérer.', en: 'You’re a secret agent: do your tasks without being spotted.' },
  { fr: 'Raconte ta journée dans ta tête comme un documentaire animalier.', en: 'Narrate your day in your head like a nature documentary.' },
  { fr: 'La famille a un mot secret aujourd’hui — clin d’œil quand quelqu’un le dit.', en: 'The family has a secret word today — wink when someone says it.', venue: 'in' },
  { fr: 'Choisis un animal ce matin et bouge un peu comme lui toute la journée.', en: 'Pick an animal this morning and move a bit like it all day.' },
  { fr: 'Donne un nom à un objet et appelle-le par son nom toute la journée.', en: 'Name an object and call it by its name all day.', venue: 'in' },
  { fr: 'Ton pouce est un micro : interviewe quelqu’un à chaque repas.', en: 'Your thumb is a mic: interview someone at each meal.', venue: 'in' },
  { fr: 'Invente le titre du film de ta journée; annonce-le au souper.', en: 'Invent the title of your day’s movie; announce it at supper.' },
  { fr: 'Chaque porte est une porte magique : dis où elle mène.', en: 'Every door is a magic door: say where it leads.', venue: 'in' },
  { fr: 'Tu es le majordome de la maison aujourd’hui : « Madame est servie. »', en: 'You’re the house butler today: “Dinner is served.”', venue: 'in' },
  { fr: 'Adopte un accent pendant tout un repas.', en: 'Adopt an accent for a whole meal.', venue: 'in' },
  { fr: 'Ta mission secrète : faire sourire chaque membre de la famille sans qu’ils sachent pourquoi.', en: 'Your secret mission: make each family member smile without them knowing why.' },
  { fr: 'Tu es un explorateur : la maison est une jungle inconnue, nomme ses régions.', en: 'You’re an explorer: the house is an unknown jungle, name its regions.', venue: 'in' },
  { fr: 'Glisse une phrase de film dans une vraie conversation sans te faire prendre.', en: 'Slip a movie line into a real conversation without getting caught.' },
  { fr: 'Tu es détective : trouve qui a bu dans quel verre.', en: 'You’re a detective: find who drank from which glass.', venue: 'in' },
  { fr: 'Invente ton nom de code du jour; réponds seulement à lui à la maison.', en: 'Invent your codename for the day; only answer to it at home.', venue: 'in' },
  { fr: 'Observe quelqu’un gentiment et note trois choses qu’il fait bien; révèle-les au souper.', en: 'Kindly observe someone and note three things they do well; reveal them at supper.' },

  // R · Connexion famille
  { fr: 'Demande à un parent sa toune préférée quand il était petit.', en: 'Ask a parent their favourite song when they were little.' },
  { fr: 'Demande à grand-maman ou grand-papa un souvenir de leur enfance.', en: 'Ask grandma or grandpa a memory from their childhood.' },
  { fr: 'Regarde des photos de bébé de quelqu’un de la famille ensemble.', en: 'Look at a family member’s baby photos together.', venue: 'in' },
  { fr: 'Demande à chacun son plus beau voyage; écoute les histoires.', en: 'Ask everyone their best trip; listen to the stories.' },
  { fr: 'Apprends une recette de famille (ou son histoire).', en: 'Learn a family recipe (or its story).', venue: 'in' },
  { fr: 'Demande à un parent la bêtise la plus drôle de SON enfance.', en: 'Ask a parent the funniest mischief of THEIR childhood.' },
  { fr: 'Appelle un cousin, une tante, un oncle juste pour jaser.', en: 'Call a cousin, an aunt or an uncle just to chat.' },
  { fr: 'Trouve qui, dans la famille, te ressemble le plus — demande aux autres.', en: 'Find who in the family is most like you — ask the others.' },
  { fr: 'Fais raconter à chacun sa journée en trois mots seulement.', en: 'Have everyone tell their day in three words only.', venue: 'in' },
  { fr: 'Demande à quelqu’un de te montrer une photo qui compte pour lui.', en: 'Ask someone to show you a photo that matters to them.' },
  { fr: 'Trouve le point commun le plus surprenant entre toi et un parent.', en: 'Find the most surprising thing you share with a parent.' },
  { fr: 'Écris ou dessine quelque chose pour la boîte aux lettres d’un proche.', en: 'Write or draw something for a loved one’s mailbox.' },
  { fr: 'Demande comment tes parents se sont rencontrés (encore une fois!).', en: 'Ask how your parents met (one more time!).' },
  { fr: 'Joue à « quand tu avais mon âge… » avec un adulte de la maison.', en: 'Play “when you were my age…” with a grown-up at home.', venue: 'in' },

  // S · Défis d'hiver
  { fr: 'Attrape un flocon sur ta mitaine et regarde-le de proche.', en: 'Catch a snowflake on your mitten and look at it close.', venue: 'out', season: 'winter' },
  { fr: 'Fais un ange dans la neige, même un petit.', en: 'Make a snow angel, even a small one.', venue: 'out', season: 'winter' },
  { fr: 'Écris ton prénom dans la neige (avec un bâton!).', en: 'Write your name in the snow (with a stick!).', venue: 'out', season: 'winter' },
  { fr: 'Repère les traces de trois animaux différents dans la neige.', en: 'Spot the tracks of three different animals in the snow.', venue: 'out', season: 'winter' },
  { fr: 'Construis le plus petit bonhomme de neige du monde.', en: 'Build the world’s tiniest snowman.', venue: 'out', season: 'winter' },
  { fr: 'Marche dans la neige qui n’a jamais été touchée.', en: 'Walk in snow no one has touched yet.', venue: 'out', season: 'winter' },
  { fr: 'Écoute le silence après une bordée.', en: 'Listen to the silence after a snowfall.', season: 'winter' },
  { fr: 'Trouve le plus beau glaçon du quartier (sans le casser… ou en le croquant!).', en: 'Find the best icicle in the neighbourhood (leave it… or crunch it!).', venue: 'out', season: 'winter' },
  { fr: 'Décore un arbre dehors avec des graines pour les oiseaux.', en: 'Decorate an outdoor tree with seeds for the birds.', venue: 'out', season: 'winter' },
  { fr: 'Fais de la buée et dessine dessus.', en: 'Fog up a window and draw on it.', season: 'winter' },
  { fr: 'Chocolat chaud obligatoire ce soir — chacun sa garniture.', en: 'Hot chocolate is mandatory tonight — everyone their own topping.', season: 'winter' },
  { fr: 'Repère de la neige qui brille comme des diamants.', en: 'Spot snow that sparkles like diamonds.', venue: 'out', season: 'winter' },

  // T · Défis d'été
  { fr: 'Marche pieds nus dans le gazon une minute.', en: 'Walk barefoot in the grass for a minute.', venue: 'out', season: 'summer' },
  { fr: 'Trouve un trèfle à quatre feuilles (ou admire ceux à trois).', en: 'Find a four-leaf clover (or admire the three-leaf ones).', venue: 'out', season: 'summer' },
  { fr: 'Fais des bulles et suis la plus grosse jusqu’au bout.', en: 'Blow bubbles and follow the biggest to the end.', venue: 'out', season: 'summer' },
  { fr: 'Bois de l’eau avec des glaçons et un fruit dedans.', en: 'Drink water with ice cubes and a fruit in it.', season: 'summer' },
  { fr: 'Trouve de l’ombre parfaite et restes-y cinq minutes.', en: 'Find perfect shade and stay in it five minutes.', venue: 'out', season: 'summer' },
  { fr: 'Cours dans l’eau (arroseur, flaque, lac — au choix!).', en: 'Run through water (sprinkler, puddle, lake — your pick!).', venue: 'out', season: 'summer' },
  { fr: 'Regarde les étoiles dix minutes ce soir.', en: 'Watch the stars for ten minutes tonight.', venue: 'out', season: 'summer' },
  { fr: 'Attrape (et relâche!) un insecte doucement.', en: 'Gently catch (and release!) an insect.', venue: 'out', season: 'summer' },
  { fr: 'Mange quelque chose dehors, même juste une collation.', en: 'Eat something outside, even just a snack.', venue: 'out', season: 'summer' },
  { fr: 'Repère cinq fleurs de couleurs différentes.', en: 'Spot five flowers of different colours.', venue: 'out', season: 'summer' },
  { fr: 'Écoute les criquets ou les grenouilles ce soir.', en: 'Listen to the crickets or frogs tonight.', venue: 'out', season: 'summer' },
  { fr: 'Trouve la chose la plus fraîche du quartier.', en: 'Find the coolest (temperature!) spot in the neighbourhood.', venue: 'out', season: 'summer' },

  // U · Pluie & mauvais temps
  { fr: 'Sors sentir la pluie trente secondes (avec ou sans parapluie).', en: 'Step out and smell the rain for thirty seconds (umbrella optional).', venue: 'out', season: 'rain' },
  { fr: 'Compte les parapluies que tu vois aujourd’hui.', en: 'Count the umbrellas you see today.', season: 'rain' },
  { fr: 'Trouve la plus grosse flaque et contourne-la… ou pas (avec bottes!).', en: 'Find the biggest puddle and go around it… or not (with boots!).', venue: 'out', season: 'rain' },
  { fr: 'Écoute la pluie sur trois surfaces différentes.', en: 'Listen to the rain on three different surfaces.', season: 'rain' },
  { fr: 'Journée cabane : construis un abri de couvertures pour la soirée.', en: 'Fort day: build a blanket shelter for the evening.', venue: 'in', season: 'rain' },
  { fr: 'Regarde l’orage par la fenêtre comme un film.', en: 'Watch the storm through the window like a movie.', venue: 'in', season: 'rain' },
  { fr: 'Cherche l’arc-en-ciel après la pluie.', en: 'Look for the rainbow after the rain.', venue: 'out', season: 'rain' },
  { fr: 'Dessine ce que tu ferais s’il faisait beau — et garde-le pour ce jour-là.', en: 'Draw what you’d do if it were sunny — and save it for that day.', venue: 'in', season: 'rain' },
  { fr: 'Trouve l’odeur de la pluie et essaie de la décrire.', en: 'Find the smell of rain and try to describe it.', season: 'rain' },
  { fr: 'Journée lampe de poche : la soirée s’éclaire autrement.', en: 'Flashlight day: light the evening differently.', venue: 'in', season: 'rain' },

  // V · Rire & absurde
  { fr: 'Parle en chuchotant pendant tout un repas.', en: 'Whisper through a whole meal.', venue: 'in' },
  { fr: 'Présente la météo du salon comme un présentateur télé.', en: 'Present the living-room weather like a TV forecaster.', venue: 'in' },
  { fr: 'Donne un titre de film dramatique à ta journée.', en: 'Give your day a dramatic movie title.' },
  { fr: 'Marche avec un livre sur la tête d’un mur à l’autre.', en: 'Walk with a book on your head from wall to wall.', venue: 'in' },
  { fr: 'Dis « oui » avec dix intonations différentes.', en: 'Say “yes” in ten different tones.' },
  { fr: 'Fais une entrevue avec ton animal ou ton toutou.', en: 'Interview your pet or your stuffed animal.', venue: 'in' },
  { fr: 'Applaudis quelqu’un qui fait quelque chose d’ordinaire.', en: 'Applaud someone doing something ordinary.' },
  { fr: 'Invente un proverbe qui n’existe pas et dis-le sérieusement.', en: 'Invent a proverb that doesn’t exist and say it seriously.' },
  { fr: 'Mange ton dessert comme si c’était la première fois de ta vie.', en: 'Eat your dessert like it’s the first time in your life.' },
  { fr: 'Concours de grimaces au brossage de dents.', en: 'Funny-face contest at tooth-brushing time.', venue: 'in' },
  { fr: 'Réponds au téléphone (ou à la porte) avec une voix inventée, une fois.', en: 'Answer the phone (or the door) with a made-up voice, once.', venue: 'in' },
  { fr: 'Fais semblant que ta cuillère est trop lourde, un repas au complet.', en: 'Pretend your spoon is too heavy, for a whole meal.', venue: 'in' },
  { fr: 'Invente une pub pour un objet ordinaire de la maison.', en: 'Invent an ad for an ordinary household object.', venue: 'in' },
  { fr: 'Raconte une blague à chaque membre de la famille.', en: 'Tell a joke to each family member.' },
  { fr: 'Ris pour vrai au moins une fois aux éclats — provoque-le s’il le faut.', en: 'Really belly-laugh at least once — make it happen if you must.' },
  { fr: 'Fais un discours de remerciement en recevant ton assiette.', en: 'Give an acceptance speech when you get your plate.', venue: 'in' },
  { fr: 'Journée « tout est incroyable » : émerveille-toi de façon exagérée.', en: '“Everything is amazing” day: marvel at things over the top.' },
  { fr: 'Invente le sport olympique le plus inutile et fais une démonstration.', en: 'Invent the most useless Olympic sport and demonstrate it.' },

  // W · Musique & sons
  { fr: 'Chante une chanson connue en voix de robot.', en: 'Sing a known song in a robot voice.' },
  { fr: 'Fredonne une toune et fais-la deviner.', en: 'Hum a tune and make them guess it.' },
  { fr: 'Écoute une musique d’un pays que tu ne connais pas.', en: 'Listen to music from a country you don’t know.' },
  { fr: 'Fais un rythme avec tes mains que tout le monde répète.', en: 'Make a hand rhythm that everyone repeats.' },
  { fr: 'Chante ce que tu fais, comme un opéra, pendant dix minutes.', en: 'Sing what you’re doing, opera-style, for ten minutes.' },
  { fr: 'Trouve la toune du jour de la famille et écoutez-la deux fois.', en: 'Find the family’s song of the day and play it twice.' },
  { fr: 'Invente une chanson d’une ligne sur le souper.', en: 'Invent a one-line song about supper.', venue: 'in' },
  { fr: 'Danse sur une toune que tes parents aimaient à ton âge.', en: 'Dance to a song your parents liked at your age.' },
  { fr: 'Écoute une chanson les yeux fermés, au complet.', en: 'Listen to a song with your eyes closed, all the way.' },
  { fr: 'Fais une chorale familiale d’UNE chanson ce soir (même faux!).', en: 'Do a family sing-along of ONE song tonight (off-key is fine!).', venue: 'in' },
  { fr: 'Trouve l’instrument caché dans une chanson (batterie? piano? basse?).', en: 'Find the hidden instrument in a song (drums? piano? bass?).' },
  { fr: 'Sifflote ou fredonne en faisant une corvée.', en: 'Whistle or hum while doing a chore.', venue: 'in' },
  { fr: 'Chacun choisit une toune : le trajet ou le souper a une trame sonore.', en: 'Everyone picks a song: the trip or supper gets a soundtrack.' },
  { fr: 'Invente un cri de ralliement familial et testez-le.', en: 'Invent a family rallying cry and test it out.' },

  // X · Maison ludique
  { fr: 'Trouve un objet qui commence par la lettre de ton prénom.', en: 'Find an object starting with your name’s first letter.', venue: 'in' },
  { fr: 'Change un cadre ou une déco de place; qui le remarquera?', en: 'Move a frame or a decoration; who will notice?', venue: 'in' },
  { fr: 'Trouve la chose la plus vieille de la maison.', en: 'Find the oldest thing in the house.', venue: 'in' },
  { fr: 'Cache un bonhomme sourire quelque part pour demain.', en: 'Hide a smiley somewhere for tomorrow.', venue: 'in' },
  { fr: 'Regarde par une fenêtre où tu ne regardes jamais.', en: 'Look out a window you never look out of.', venue: 'in' },
  { fr: 'Construis la plus haute tour possible avec ce que tu trouves.', en: 'Build the tallest tower you can with what you find.', venue: 'in' },
  { fr: 'Fais un bonhomme avec des objets de la cuisine.', en: 'Make a little character out of kitchen objects.', venue: 'in' },
  { fr: 'Invente un drapeau pour la famille.', en: 'Invent a flag for the family.', venue: 'in' },
  { fr: 'Trouve un endroit de la maison où tu ne t’es jamais assis.', en: 'Find a spot in the house you’ve never sat in.', venue: 'in' },
  { fr: 'Compte les portes de la maison (les armoires comptent-elles? débattez!).', en: 'Count the doors in the house (do cupboards count? debate it!).', venue: 'in' },
  { fr: 'Trouve cinq choses bleues dans la maison en deux minutes.', en: 'Find five blue things in the house in two minutes.', venue: 'in' },
  { fr: 'Fais une exposition d’art sur une tablette : trois objets, des étiquettes.', en: 'Curate an art show on a shelf: three objects, with labels.', venue: 'in' },
  { fr: 'Renomme les pièces de la maison pour la journée (la cuisine devient…?).', en: 'Rename the rooms for the day (the kitchen becomes…?).', venue: 'in' },
  { fr: 'Trouve le meilleur écho ou le meilleur coin pour chuchoter.', en: 'Find the best echo or the best whispering corner.', venue: 'in' },
  { fr: 'Fais un parcours à obstacles doux dans le salon.', en: 'Set up a gentle obstacle course in the living room.', venue: 'in' },
  { fr: 'Organise un pique-nique par terre, rideaux fermés, comme en camping.', en: 'Set up a floor picnic, curtains closed, like camping.', venue: 'in' },
  { fr: 'Trouve l’objet le plus inutile de la maison et défends-le au souper.', en: 'Find the most useless object in the house and defend it at supper.', venue: 'in' },
  { fr: 'Éteins les lumières cinq minutes ce soir : chandelle ou lampe de poche.', en: 'Turn the lights off for five minutes tonight: candle or flashlight.', venue: 'in' },

  // Y · Petits courages
  { fr: 'Essaie quelque chose que tu rates d’habitude, une fois de plus.', en: 'Try something you usually fail at, one more time.' },
  { fr: 'Pose LA question que tu n’oses pas poser (gentille!).', en: 'Ask THE question you don’t dare ask (a kind one!).' },
  { fr: 'Goûte l’aliment que tu boudes depuis toujours, UNE bouchée.', en: 'Taste the food you’ve always avoided, ONE bite.' },
  { fr: 'Lève la main (ou parle) une fois de plus que d’habitude aujourd’hui.', en: 'Raise your hand (or speak up) one more time than usual today.' },
  { fr: 'Dis « je ne sais pas » fièrement au moins une fois.', en: 'Say “I don’t know” proudly at least once.' },
  { fr: 'Demande de l’aide pour une chose que tu fais toujours seul.', en: 'Ask for help with something you always do alone.' },
  { fr: 'Fais quelque chose de nouveau devant quelqu’un, même imparfaitement.', en: 'Do something new in front of someone, even imperfectly.' },
  { fr: 'Excuse-toi pour une petite chose, sans « mais ».', en: 'Apologize for a small thing, with no “but”.' },
  { fr: 'Dis à quelqu’un ce que tu admires chez lui, en face.', en: 'Tell someone what you admire about them, to their face.' },
  { fr: 'Choisis en premier au lieu de dire « ça me dérange pas ».', en: 'Choose first instead of saying “I don’t mind”.' },
  { fr: 'Montre à la famille une chose que tu pratiques en secret.', en: 'Show the family something you practise in secret.', venue: 'in' },
  { fr: 'Va au bout d’une chose commencée avant de commencer autre chose.', en: 'Finish one started thing before beginning another.' },
  { fr: 'Prends la parole pour proposer l’activité de la fin de semaine.', en: 'Speak up and propose the weekend activity.' },
  { fr: 'Danse le premier, chante le premier, plonge le premier — une fois.', en: 'Dance first, sing first, dive in first — once.' },

  // Z · Défis d'équipe (toute la maisonnée ensemble)
  { fr: 'La famille au complet garde une plante, un mot ou un geste secret aujourd’hui.', en: 'The whole family keeps one plant, word or gesture secret today.' },
  { fr: 'Tout le monde mange en pique-nique par terre ce soir.', en: 'Everyone eats a floor picnic tonight.', venue: 'in' },
  { fr: 'Souper aux chandelles un mardi, juste parce que.', en: 'Candle-lit supper on a Tuesday, just because.', venue: 'in' },
  { fr: 'Toute la famille apprend le même mot dans une nouvelle langue.', en: 'The whole family learns the same word in a new language.' },
  { fr: 'Chacun échange une corvée avec quelqu’un d’autre aujourd’hui.', en: 'Everyone swaps one chore with someone else today.', venue: 'in' },
  { fr: 'Marche familiale après le souper, même dix minutes.', en: 'Family walk after supper, even ten minutes.', venue: 'out' },
  { fr: 'Tout le monde se couche quinze minutes plus tôt, pour lire.', en: 'Everyone goes to bed fifteen minutes early, to read.' },
  { fr: 'La famille invente sa poignée de main officielle.', en: 'The family invents its official handshake.' },
  { fr: 'Chacun raconte sa journée en mimant seulement; les autres devinent.', en: 'Everyone tells their day by miming only; the others guess.', venue: 'in' },
  { fr: 'Photo de famille sautée (tout le monde dans les airs!).', en: 'Family jump photo (everyone in the air!).' },
  { fr: 'Le souper se passe dans une autre pièce que d’habitude.', en: 'Supper happens in a different room than usual.', venue: 'in' },
  { fr: 'Chacun apporte UNE devinette au souper.', en: 'Everyone brings ONE riddle to supper.', venue: 'in' },
  { fr: 'Toute la famille dessine le même objet; expo sur le frigo.', en: 'The whole family draws the same object; show it on the fridge.', venue: 'in' },
  { fr: 'Soirée « comme avant » : zéro écran après le souper, jeux et histoires.', en: '“Like the old days” evening: zero screens after supper, games and stories.', venue: 'in' },
  { fr: 'Tout le monde aide à faire le souper, chacun UNE étape.', en: 'Everyone helps make supper, one step each.', venue: 'in' },
  { fr: 'La famille choisit ensemble le défi de demain.', en: 'The family picks tomorrow’s challenge together.' },

  // AA · Rythmes du matin & du soir
  { fr: 'Lève-toi au premier réveil, sans « encore cinq minutes ».', en: 'Get up on the first alarm, no “five more minutes”.' },
  { fr: 'Fais entrer la lumière partout dès le matin : rideaux grands ouverts.', en: 'Let light in everywhere first thing: curtains wide open.', venue: 'in' },
  { fr: 'Dis « bon matin » à chaque personne AVANT de parler d’autre chose.', en: 'Say “good morning” to each person BEFORE anything else.' },
  { fr: 'Prépare un déjeuner un peu spécial, même juste joliment coupé.', en: 'Make a slightly special breakfast, even just nicely cut.', venue: 'in' },
  { fr: 'Sors dehors dans les trente premières minutes de ta journée.', en: 'Get outside within the first thirty minutes of your day.', venue: 'out' },
  { fr: 'Pas de nouvelles ni d’écran avant le déjeuner.', en: 'No news and no screens before breakfast.' },
  { fr: 'Fais une chose difficile EN PREMIER ce matin.', en: 'Do one hard thing FIRST this morning.' },
  { fr: 'Ce soir, raconte une histoire au lieu d’un écran.', en: 'Tonight, tell a story instead of a screen.' },
  { fr: 'Prépare le déjeuner de demain ce soir, comme un cadeau à toi-même.', en: 'Prep tomorrow’s breakfast tonight, like a gift to yourself.', venue: 'in' },
  { fr: 'Couche-toi sans téléphone dans la chambre ce soir.', en: 'Go to bed with no phone in the room tonight.' },
  { fr: 'Termine la journée en rangeant dix choses, tous ensemble, en musique.', en: 'End the day tidying ten things, all together, to music.', venue: 'in' },
  { fr: 'Dis bonne nuit à chaque personne ET chaque animal de la maison.', en: 'Say good night to each person AND each pet in the house.', venue: 'in' },

  // BB · Générosité de temps
  { fr: 'Offre quinze minutes de TON temps à quelqu’un : il choisit quoi faire.', en: 'Give someone fifteen minutes of YOUR time: they pick what to do.' },
  { fr: 'Joue au jeu préféré de quelqu’un d’autre, sans négocier.', en: 'Play someone else’s favourite game, no negotiating.' },
  { fr: 'Lis une histoire à quelqu’un (ou fais-toi en lire une).', en: 'Read someone a story (or have one read to you).' },
  { fr: 'Aide quelqu’un à finir sa corvée pour qu’on ait du temps ensemble.', en: 'Help someone finish their chore so you get time together.', venue: 'in' },
  { fr: 'Regarde quelqu’un faire sa passion et pose trois questions.', en: 'Watch someone do their passion and ask three questions.' },
  { fr: 'Laisse quelqu’un te montrer SON jeu vidéo / sa musique / son livre.', en: 'Let someone show you THEIR video game / music / book.' },
  { fr: 'Fais une promenade au rythme du plus lent, sans presser.', en: 'Take a walk at the slowest person’s pace, no rushing.', venue: 'out' },
  { fr: 'Attends que tout le monde soit servi avant de commencer à manger.', en: 'Wait until everyone is served before you start eating.', venue: 'in' },
  { fr: 'Reste à table jusqu’à ce que TOUT le monde ait fini.', en: 'Stay at the table until EVERYONE is done.', venue: 'in' },
  { fr: 'Propose « on le fait ensemble? » au lieu de « as-tu fini? », toute la journée.', en: 'Offer “shall we do it together?” instead of “are you done?”, all day.' },

  // CC · Espiègle mais gentil
  { fr: 'Mets un accessoire au toutou / à la statue / à la plante de la maison.', en: 'Put an accessory on the stuffed animal / statue / house plant.', venue: 'in' },
  { fr: 'Remplace le fond d’écran de famille par un dessin (avec permission!).', en: 'Swap the family wallpaper for a drawing (with permission!).', venue: 'in' },
  { fr: 'Glisse un mot mystère dans la boîte à lunch de quelqu’un.', en: 'Slip a mystery note into someone’s lunchbox.', venue: 'in' },
  { fr: 'Réponds « oui votre majesté » à une demande, une fois.', en: 'Answer “yes your majesty” to one request, once.' },
  { fr: 'Mets la chanson préférée de quelqu’un quand il entre dans la pièce.', en: 'Play someone’s favourite song as they walk into the room.', venue: 'in' },
  { fr: 'Fais un faux menu du souper avec des noms de plats inventés.', en: 'Make a fake supper menu with invented dish names.', venue: 'in' },
  { fr: 'Applaudis quand quelqu’un réussit à ouvrir un pot difficile.', en: 'Cheer when someone finally opens a stubborn jar.', venue: 'in' },
  { fr: 'Instaure un mot interdit au souper; qui le dit fait la vaisselle d’un couvert.', en: 'Set a forbidden word at supper; whoever says it does one setting’s dishes.', venue: 'in' },
  { fr: 'Parle du chat comme s’il était le patron de la maison.', en: 'Talk about the cat as if it runs the house.', venue: 'in' },
  { fr: 'Fais une annonce officielle pour une nouvelle minuscule (« la plante a une nouvelle feuille! »).', en: 'Make an official announcement for a tiny news item (“the plant has a new leaf!”).', venue: 'in' },

  // DD · Curiosité de quartier
  { fr: 'Trouve le plus vieux bâtiment que tu croises aujourd’hui.', en: 'Find the oldest building you pass today.', venue: 'out' },
  { fr: 'Repère une enseigne drôle ou étrange.', en: 'Spot a funny or strange sign.', venue: 'out' },
  { fr: 'Découvre le nom de ta rue : qui ou quoi c’était?', en: 'Find out your street’s name: who or what was it?' },
  { fr: 'Trouve un commerce devant lequel tu passes sans jamais entrer — regarde la vitrine.', en: 'Find a shop you pass but never enter — look in the window.', venue: 'out' },
  { fr: 'Repère trois boîtes aux lettres différentes.', en: 'Spot three different mailboxes.', venue: 'out' },
  { fr: 'Trouve une borne-fontaine et sa couleur (elles ont un code!).', en: 'Find a fire hydrant and its colour (they’re colour-coded!).', venue: 'out' },
  { fr: 'Compte les balcons fleuris de ta rue.', en: 'Count the flowered balconies on your street.', venue: 'out', season: 'summer' },
  { fr: 'Trouve le chat du quartier (chaque quartier en a un).', en: 'Find the neighbourhood cat (every area has one).', venue: 'out' },
  { fr: 'Repère une girouette, une antenne rigolote ou une cheminée spéciale.', en: 'Spot a weathervane, a funny antenna or a special chimney.', venue: 'out' },
  { fr: 'Trouve d’où vient le meilleur fumet de cuisine du quartier, vers 17 h.', en: 'Track down the best cooking smell in the neighbourhood around 5pm.', venue: 'out' },
  { fr: 'Cherche le plus beau jardin (ou balcon) à trois rues autour.', en: 'Look for the nicest garden (or balcony) within three streets.', venue: 'out' },
  { fr: 'Repère un nid, une ruche ou une mangeoire.', en: 'Spot a nest, a hive or a bird feeder.', venue: 'out' },
  { fr: 'Salue le commerçant le plus proche de chez toi par son nom.', en: 'Greet the shopkeeper nearest your home by name.', needs: 'people' },
  { fr: 'Trouve une trace de l’ancien temps : rail, pub peinte, borne, date gravée.', en: 'Find a trace of the old days: a rail, a painted ad, a marker, a carved date.', venue: 'out' },

  // EE · Douceur pour soi
  { fr: 'Bois ton premier verre d’eau avant toute autre chose ce matin.', en: 'Drink your first glass of water before anything else this morning.' },
  { fr: 'Prends dix vraies minutes pour toi, sans culpabilité, et nomme-les.', en: 'Take ten real minutes for yourself, guilt-free, and name them.' },
  { fr: 'Habille-toi avec ce qui te rend LE plus à l’aise aujourd’hui.', en: 'Dress in whatever makes you MOST comfortable today.', needs: 'clothes' },
  { fr: 'Dis une chose gentille sur toi-même à voix haute (oui, tout haut).', en: 'Say one kind thing about yourself out loud (yes, out loud).' },
  { fr: 'Fais UNE chose que tu remets depuis une semaine — juste une.', en: 'Do ONE thing you’ve put off for a week — just one.' },
  { fr: 'Prends ta collation préférée sans la partager, sans t’excuser.', en: 'Have your favourite snack without sharing, without apologizing.' },
  { fr: 'Étire-toi trois fois aujourd’hui, aux moments de ton choix.', en: 'Stretch three times today, whenever you choose.' },
  { fr: 'Va dehors cinq minutes, seul, sans but.', en: 'Go outside for five minutes, alone, with no purpose.', venue: 'out' },
  { fr: 'Écris (ou dis) une inquiétude, puis range-la pour demain.', en: 'Write (or say) one worry, then set it aside for tomorrow.' },
  { fr: 'Couche-toi quand tu es fatigué, pas quand l’écran a fini.', en: 'Go to bed when you’re tired, not when the screen is done.' },
  { fr: 'Regarde-toi dans le miroir et fais-toi un clin d’œil.', en: 'Look in the mirror and give yourself a wink.' },
  { fr: 'Pardonne-toi une petite affaire d’hier, officiellement.', en: 'Forgive yourself for one small thing from yesterday, officially.' },
]
