// The one shared emoji palette, used everywhere a person taps to pick a glyph — a
// routine card (CardDeckEditor), a carnet (a house / car / thing), and any future
// picker. Deliberately BROAD ("show 'em all"): a routine wants toothbrushes and
// breakfast, a carnet wants houses, cars and DIY/upkeep tools — so one generous,
// curated set serves both rather than each place hand-rolling a narrow list.
//
// Grouped by theme in source for maintenance; rendered as one flat scrollable grid
// (EmojiPicker). Add to whichever group fits — order here is the order shown.
export const EMOJI_SET = [
  // Day parts · routines · self-care (the original routine-card set)
  '🌅', '☀️', '🌙', '⭐', '😴', '🙂', '🪥', '🛁', '🚿', '🧼', '🧴', '🚽', '🧻',
  // Home · rooms · furniture · appliances
  '🏠', '🏡', '🏢', '🏘️', '🛏️', '🛋️', '🚪', '🪟', '🪑', '🚰', '🔌', '💡', '🔋',
  '🧹', '🧽', '🧺', '🧼', '🗑️', '🧯', '🌡️', '🪣', '📦', '🔑', '🗝️',
  // Cars · vehicles · transport (carnets: l'auto)
  '🚗', '🚙', '🛻', '🚐', '🏎️', '🚕', '🚲', '🏍️', '🛵', '🛴', '⛽', '🅿️', '🛞', '🚧',
  // Tools · DIY · maintenance (carnets: entretien)
  '🔧', '🔨', '🪛', '🪚', '🧰', '⚙️', '🔩', '🪜', '🧲', '🪝', '🔦', '🧱', '🪵', '🩹',
  // Clothing · laundry
  '👕', '👚', '🧦', '👟', '🧥', '👗', '🧢', '🧤', '🧣',
  // Food · drink · cooking
  '🍽️', '🥞', '🍳', '🥛', '☕', '🍞', '🧀', '🥗', '🍕', '🍝', '🍎', '🍌', '🥕', '🥦',
  '🍓', '🍇', '🥔', '🧅', '🍅', '🥚', '🍰', '🍪', '🍫',
  // Play · sport · hobbies · music · art
  '🧸', '🎨', '📚', '📖', '✏️', '⚽', '🏀', '🏒', '🎾', '🚴', '🏊', '🎣', '🎮', '🧩',
  '🎵', '🎸', '🎹', '🥁', '🎤', '🎬', '🃏', '🎲',
  // Nature · animals · plants · weather
  '🌱', '🌳', '🌲', '🌸', '🌼', '🍁', '🐟', '🐶', '🐱', '🐰', '🐦', '🐢', '🐝', '🦋',
  '❄️', '🔥', '💧', '⚡', '🌧️', '🌈', '⛄',
  // Health · care · time
  '❤️', '🩺', '💊', '🦷', '🧬', '🌡️', '⏰', '📅', '🔔', '📌', '📎', '✅', '⚠️',
  // People · family · celebration
  '👶', '🧒', '👦', '👧', '🧑', '👩', '👨', '👵', '👴', '🎂', '🎈', '🎁', '🎉', '💌',
  // Money · shopping · work
  '💰', '💵', '🛒', '🏷️', '🧾', '💼', '🏦', '📈', '🖥️', '📱', '📷', '🔒',
]

// Search keywords per glyph (FR + EN, space-separated) so a person can type « eau »,
// « outil », « chien » to find one instead of scrolling the whole set. Matching is
// accent- and case-insensitive (see `filterEmojis`). Keep a glyph's terms short and
// obvious; add the ones you'd actually type. A glyph missing from here is still shown
// (it just can't be found by text) — so this never has to be exhaustive to be useful.
const EMOJI_KEYWORDS: Record<string, string> = {
  '🌅': 'sunrise dawn matin lever soleil aube',
  '☀️': 'sun soleil jour day beau',
  '🌙': 'moon lune nuit night soir dodo',
  '⭐': 'star etoile favori',
  '😴': 'sleep dormir sommeil nuit dodo sieste',
  '🙂': 'smile sourire visage face content',
  '🪥': 'toothbrush brosse dents dentifrice',
  '🛁': 'bath bain baignoire',
  '🚿': 'shower douche',
  '🧼': 'soap savon',
  '🧴': 'lotion creme flacon bouteille shampooing',
  '🚽': 'toilet toilette wc',
  '🧻': 'paper papier toilette rouleau roll',
  '🏠': 'house maison home chez',
  '🏡': 'house maison jardin home',
  '🏢': 'building immeuble bureau office',
  '🏘️': 'houses maisons quartier',
  '🛏️': 'bed lit chambre',
  '🛋️': 'couch sofa divan salon canape',
  '🚪': 'door porte',
  '🪟': 'window fenetre',
  '🪑': 'chair chaise siege',
  '🚰': 'water eau robinet tap potable plomberie',
  '🔌': 'plug prise electrique electric branchement',
  '💡': 'light lumiere ampoule idea idee',
  '🔋': 'battery batterie pile',
  '🧹': 'broom balai menage',
  '🧽': 'sponge eponge',
  '🧺': 'basket panier linge laundry lessive',
  '🗑️': 'trash poubelle dechet garbage ordures',
  '🧯': 'extinguisher extincteur feu fire securite',
  '🌡️': 'thermometer thermometre temperature fievre',
  '🪣': 'bucket seau chaudiere',
  '📦': 'box boite carton colis chose thing',
  '🔑': 'key cle clef',
  '🗝️': 'key cle clef ancienne',
  '🚗': 'car auto voiture char',
  '🚙': 'suv voiture auto vus',
  '🛻': 'truck camionnette pickup',
  '🚐': 'van fourgonnette minibus',
  '🏎️': 'race car course voiture sport',
  '🚕': 'taxi',
  '🚲': 'bike velo bicyclette',
  '🏍️': 'motorcycle moto',
  '🛵': 'scooter mobylette',
  '🛴': 'scooter trottinette',
  '⛽': 'gas essence carburant fuel pompe',
  '🅿️': 'parking stationnement',
  '🛞': 'tire pneu roue wheel',
  '🚧': 'construction chantier travaux',
  '🔧': 'wrench cle outil mecanique',
  '🔨': 'hammer marteau',
  '🪛': 'screwdriver tournevis',
  '🪚': 'saw scie',
  '🧰': 'toolbox coffre outils boite',
  '⚙️': 'gear engrenage reglage settings mecanique entretien',
  '🔩': 'bolt boulon vis',
  '🪜': 'ladder echelle',
  '🧲': 'magnet aimant',
  '🪝': 'hook crochet',
  '🔦': 'flashlight lampe torche',
  '🧱': 'brick brique mur',
  '🪵': 'wood bois planche',
  '🩹': 'bandage pansement reparation fix',
  '👕': 'tshirt shirt chandail vetement linge',
  '👚': 'blouse chemisier vetement',
  '🧦': 'socks bas chaussettes',
  '👟': 'shoe soulier chaussure basket',
  '🧥': 'coat manteau',
  '👗': 'dress robe',
  '🧢': 'cap casquette chapeau',
  '🧤': 'gloves gants mitaines',
  '🧣': 'scarf foulard echarpe',
  '🍽️': 'plate assiette repas meal souper diner',
  '🥞': 'pancakes crepes dejeuner',
  '🍳': 'egg oeuf cuisine cooking poele',
  '🥛': 'milk lait verre',
  '☕': 'coffee cafe the',
  '🍞': 'bread pain',
  '🧀': 'cheese fromage',
  '🥗': 'salad salade',
  '🍕': 'pizza',
  '🍝': 'pasta pates spaghetti',
  '🍎': 'apple pomme fruit',
  '🍌': 'banana banane fruit',
  '🥕': 'carrot carotte legume',
  '🥦': 'broccoli brocoli legume',
  '🍓': 'strawberry fraise fruit',
  '🍇': 'grapes raisin fruit',
  '🥔': 'potato patate',
  '🧅': 'onion oignon',
  '🍅': 'tomato tomate',
  '🥚': 'egg oeuf',
  '🍰': 'cake gateau dessert',
  '🍪': 'cookie biscuit',
  '🍫': 'chocolate chocolat',
  '🧸': 'teddy toutou ourson jouet toy',
  '🎨': 'art peinture palette dessin',
  '📚': 'books livres',
  '📖': 'book livre carnet',
  '✏️': 'pencil crayon',
  '⚽': 'soccer football ballon',
  '🏀': 'basketball ballon',
  '🏒': 'hockey',
  '🎾': 'tennis',
  '🚴': 'cycling velo',
  '🏊': 'swim natation nager piscine',
  '🎣': 'fishing peche',
  '🎮': 'game jeu video manette',
  '🧩': 'puzzle casse-tete',
  '🎵': 'music musique note',
  '🎸': 'guitar guitare',
  '🎹': 'piano clavier',
  '🥁': 'drums batterie tambour',
  '🎤': 'mic micro chant karaoke',
  '🎬': 'movie film cinema',
  '🃏': 'card carte joker',
  '🎲': 'dice de jeu',
  '🌱': 'sprout plante semis pousse',
  '🌳': 'tree arbre',
  '🌲': 'tree arbre sapin conifere',
  '🌸': 'flower fleur cerisier',
  '🌼': 'flower fleur marguerite',
  '🍁': 'leaf feuille automne',
  '🐟': 'fish poisson',
  '🐶': 'dog chien',
  '🐱': 'cat chat',
  '🐰': 'rabbit lapin',
  '🐦': 'bird oiseau',
  '🐢': 'turtle tortue',
  '🐝': 'bee abeille',
  '🦋': 'butterfly papillon',
  '❄️': 'snow neige flocon hiver',
  '🔥': 'fire feu chauffage flamme',
  '💧': 'water eau goutte',
  '⚡': 'electric electricite eclair energie',
  '🌧️': 'rain pluie',
  '🌈': 'rainbow arc-en-ciel',
  '⛄': 'snowman bonhomme neige',
  '❤️': 'heart coeur amour sante favori',
  '🩺': 'stethoscope docteur medecin sante',
  '💊': 'pill medicament pilule',
  '🦷': 'tooth dent dentiste',
  '🧬': 'dna genetique sante',
  '⏰': 'alarm reveil horloge temps',
  '📅': 'calendar calendrier date',
  '🔔': 'bell cloche rappel notification',
  '📌': 'pin epingle punaise',
  '📎': 'clip trombone attache document',
  '✅': 'check coche fait valide done',
  '⚠️': 'warning attention avertissement danger',
  '👶': 'baby bebe',
  '🧒': 'child enfant',
  '👦': 'boy garcon',
  '👧': 'girl fille',
  '🧑': 'person personne adulte',
  '👩': 'woman femme',
  '👨': 'man homme',
  '👵': 'grandma grand-mere mamie',
  '👴': 'grandpa grand-pere papi',
  '🎂': 'birthday gateau anniversaire fete',
  '🎈': 'balloon ballon fete',
  '🎁': 'gift cadeau',
  '🎉': 'party fete celebration',
  '💌': 'letter lettre carte message amour',
  '💰': 'money argent sac',
  '💵': 'cash argent billet dollar',
  '🛒': 'cart panier epicerie achat shopping',
  '🏷️': 'tag etiquette prix rabais',
  '🧾': 'receipt recu facture achat',
  '💼': 'briefcase mallette travail bureau',
  '🏦': 'bank banque',
  '📈': 'chart graphique croissance',
  '🖥️': 'computer ordinateur ecran',
  '📱': 'phone telephone cellulaire',
  '📷': 'camera appareil photo',
  '🔒': 'lock cadenas securite verrou',
}

// Fold accents + lowercase so « eau » matches "eau" and « écran » matches "ecran".
function fold(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .trim()
}

// The subset of EMOJI_SET matching a free-text query (by keyword). Empty query → the
// whole set. A query that is itself an emoji (pasted) matches that glyph directly.
export function filterEmojis(query: string): string[] {
  const q = fold(query)
  if (!q) return EMOJI_SET
  return EMOJI_SET.filter((e) => e === query.trim() || fold(EMOJI_KEYWORDS[e] ?? '').includes(q))
}
