import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'

// SPA build. The app is a Cloudflare Worker with static assets: worker/index.ts
// serves dist/ and routes /api/* to the handlers in functions/. Local full-stack
// dev is `npm run cf:dev` (wrangler dev — serves assets + Worker on :8787);
// plain `vite` gives a frontend-only loop with HMR and the API proxied to that
// wrangler instance. Test config lives in vitest.config.ts (kept separate so the
// two vite copies don't clash in tsc).

// Files Vite copies from public/ (not part of the bundle object) that the app
// shell needs offline — keep in sync with public/.
const PUBLIC_SHELL = [
  '/',
  '/manifest.webmanifest',
  '/theme-bootstrap.js',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/icon-maskable-512.png',
  '/icons/apple-touch-icon.png',
]

// Build-time service worker: emit /sw.js with the REAL hashed asset list baked
// in, so a freshly-installed kiosk precaches the whole shell and reboots fine
// offline (NFR-OFFLINE-1). Hand-rolled and dependency-free on purpose — the
// caching policy is a dozen lines (see swSource) and the asset list is the only
// thing a build truly knows better than runtime.
function serviceWorker(): Plugin {
  return {
    name: 'babillard-sw',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const assets = Object.keys(bundle)
        .filter((f) => !f.endsWith('.map') && f !== 'index.html')
        .map((f) => '/' + f)
      const precache = [...PUBLIC_SHELL, ...assets]
      // djb2 over the precache list → a stable per-build cache version, so a
      // redeploy installs fresh and activate() drops the old cache.
      let h = 5381
      for (const c of precache.join('|')) h = ((h * 33) ^ c.charCodeAt(0)) >>> 0
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(h.toString(36), precache) })
    },
  }
}

const swSource = (version: string, precache: string[]) => `// Generated by vite.config.ts (babillard-sw) — do not edit.
// Offline app shell for the wall tablet / iPad PWA:
//   • precache: the built shell (this build's hashed assets + public files)
//   • navigations: network-first, falling back to the cached shell offline
//   • /api/img/* and /api/flyer-img: cache-first (immutable bytes — capability-key
//     photos, and Flipp clippings the "download for offline" step pre-warms)
//   • every other /api/*: untouched — data freshness stays TanStack's job
//     (it already keeps the last good frame + the "offline" stamp)
//   • Google Fonts: cache-as-you-go so type survives wifi loss
const CACHE = 'babillard-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 1)}

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)

  // Cross-origin: only the font CDNs, cached as they're fetched.
  if (url.origin !== location.origin) {
    if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
      e.respondWith(
        caches.match(req).then((hit) =>
          hit ?? fetch(req).then((res) => {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
            return res
          }),
        ),
      )
    }
    return
  }

  // Immutable image bytes → cache-first: capability-keyed photos (/api/img/) and
  // proxied Flipp clippings (/api/flyer-img), which the offline download pre-warms.
  if (url.pathname.startsWith('/api/img/') || url.pathname.startsWith('/api/flyer-img')) {
    e.respondWith(
      caches.match(req).then((hit) =>
        hit ?? fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
          }
          return res
        }),
      ),
    )
    return
  }

  // Live data: hands off — the query layer owns freshness and offline grace.
  if (url.pathname.startsWith('/api/')) return

  // App navigations: try the network (fresh HTML after a deploy), fall back to
  // the cached shell so an offline reboot still boots the board.
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('/')))
    return
  }

  // Static assets (hashed → immutable): cache-first, populate on miss.
  e.respondWith(
    caches.match(req).then((hit) =>
      hit ?? fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone()
          caches.open(CACHE).then((c) => c.put(req, copy))
        }
        return res
      }),
    ),
  )
})
`

export default defineConfig({
  plugins: [react(), serviceWorker()],
  server: {
    proxy: {
      // Defaults to the local wrangler instance. Override with BABILLARD_API_PROXY
      // to point the frontend dev loop at a deployed Worker (e.g. real-data e2e
      // against prod) — changeOrigin so the Worker sees its own Host; the host-only
      // session cookies then land on 127.0.0.1 so login persists across the proxy.
      '/api': {
        target: process.env.BABILLARD_API_PROXY || 'http://127.0.0.1:8787',
        changeOrigin: true,
        secure: true,
      },
    },
  },
})
