import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'

// SPA build. The app is a Cloudflare Worker with static assets: worker/index.ts
// serves dist/ and routes /api/* to the handlers in functions/. Local full-stack
// dev is `npm run cf:dev` (wrangler dev — serves assets + Worker on :8787);
// plain `vite` gives a frontend-only loop with HMR and the API proxied to that
// wrangler instance. Test config lives in vitest.config.ts (kept separate so the
// two vite copies don't clash in tsc).

// Files Vite copies from public/ (not part of the bundle object) that the app
// shell needs offline — keep in sync with public/.
const PUBLIC_SHELL = [
  '/',
  '/manifest.webmanifest',
  '/theme-bootstrap.js',
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/icon-maskable-512.png',
  '/icons/apple-touch-icon.png',
]

// C-23 (bmad/08): chunks deliberately EXCLUDED from the kiosk precache because
// their feature is ONLINE-ONLY — an offline reboot can never need them, and
// precaching them taxes every install. heic2any is the ~1.3 MB wasm HEIC
// decoder used only while UPLOADING an iPhone photo (Blob writes never queue —
// OFFLINE.md); it still loads on first use online and the SW's cache-first
// asset handler runtime-caches it then. Every OTHER lazy chunk MUST stay
// precached (a kiosk rebooting offline must open every lazy route) — the
// load-bearing constraint scripts/check-bundle.mjs enforces BOTH sides of in CI.
// Keep this list in sync with ONLINE_ONLY in that script.
// B-11 (bmad/10): DevKit (/dev/kit) joins the list — a dev-only component
// gallery, never a kiosk surface; accept no offline /dev/kit rather than tax
// every install with its specimen chrome. guideContent stays precached — it's
// the real offline-facing surface (the in-app Guide).
const ONLINE_ONLY_CHUNKS = [/^assets\/heic2any-/, /^assets\/DevKit-/]

// Build-time service worker: emit /sw.js with the REAL hashed asset list baked
// in, so a freshly-installed kiosk precaches the whole shell and reboots fine
// offline (NFR-OFFLINE-1). Hand-rolled and dependency-free on purpose — the
// caching policy is a dozen lines (see swSource) and the asset list is the only
// thing a build truly knows better than runtime.
function serviceWorker(): Plugin {
  return {
    name: 'babillard-sw',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const assets = Object.keys(bundle)
        .filter((f) => !f.endsWith('.map') && f !== 'index.html')
        .filter((f) => !ONLINE_ONLY_CHUNKS.some((re) => re.test(f)))
        .map((f) => '/' + f)
      const precache = [...PUBLIC_SHELL, ...assets]
      // djb2 over the precache list → a stable per-build cache version, so a
      // redeploy installs fresh and activate() drops the old cache.
      let h = 5381
      for (const c of precache.join('|')) h = ((h * 33) ^ c.charCodeAt(0)) >>> 0
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: swSource(h.toString(36), precache) })
    },
  }
}

const swSource = (version: string, precache: string[]) => `// Generated by vite.config.ts (babillard-sw) — do not edit.
// Offline app shell for the wall tablet / iPad PWA:
//   • precache: the built shell (this build's hashed assets + public files)
//   • navigations: network-first, falling back to the cached shell offline
//   • /api/img/* and /api/flyer-img: cache-first (immutable bytes — capability-key
//     photos, and Flipp clippings the "download for offline" step pre-warms)
//   • every other /api/*: untouched — data freshness stays TanStack's job
//     (it already keeps the last good frame + the "offline" stamp)
//   • Google Fonts: cache-as-you-go so type survives wifi loss
const CACHE = 'babillard-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 1)}

self.addEventListener('install', (e) => {
  // Cache each shell entry INDEPENDENTLY (allSettled), not atomically (addAll):
  // addAll rejects the whole batch if any one URL 404s or fails, which on a first
  // install would leave NOTHING cached — including the JS bundle — so the tablet
  // never boots offline (NFR-OFFLINE-1). With allSettled a single renamed/missing
  // public asset can't take the shell down with it; '/' and the hashed bundles
  // (which always exist for this build) still precache.
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => Promise.allSettled(PRECACHE.map((u) => c.add(u))))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && k !== 'babillard-share').map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (e) => {
  const req = e.request
  const url = new URL(req.url)

  // PWA share-target (#13 photos): the OS POSTs the shared payload to /share. A
  // POST navigation body can't be read by the SPA, so we intercept it here, stash
  // the image + text fields in a side cache, and 303-redirect to a GET the page
  // can read. SharePage drains 'babillard-share' on load.
  if (req.method === 'POST' && url.pathname === '/share') {
    e.respondWith((async () => {
      try {
        const form = await req.formData()
        const cache = await caches.open('babillard-share')
        const file = form.get('files')
        if (file && typeof file !== 'string' && file.size > 0) {
          await cache.put('/__share/file', new Response(file, { headers: { 'content-type': file.type || 'application/octet-stream' } }))
        } else {
          await cache.delete('/__share/file')
        }
        const meta = { title: form.get('title') || '', text: form.get('text') || '', url: form.get('url') || '' }
        await cache.put('/__share/meta', new Response(JSON.stringify(meta), { headers: { 'content-type': 'application/json' } }))
      } catch (_) { /* malformed share — fall through to an empty /share */ }
      return Response.redirect('/share?shared=1', 303)
    })())
    return
  }

  if (req.method !== 'GET') return

  // Cross-origin: only the font CDNs, cached as they're fetched.
  if (url.origin !== location.origin) {
    if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
      e.respondWith(
        caches.match(req).then((hit) =>
          hit ?? fetch(req).then((res) => {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
            return res
          }),
        ),
      )
    }
    return
  }

  // Immutable image bytes → cache-first: capability-keyed photos (/api/img/) and
  // proxied Flipp clippings (/api/flyer-img), which the offline download pre-warms.
  // On a network-level fetch reject (upstream unreachable, connection dropped) fall
  // back to any cached copy, else a synthetic 504 — never let respondWith reject, or
  // the browser logs "ServiceWorker intercepted the request and encountered an
  // unexpected error" and the <img> breaks with no clean failure.
  if (url.pathname.startsWith('/api/img/') || url.pathname.startsWith('/api/flyer-img')) {
    e.respondWith(
      caches.match(req).then((hit) =>
        hit ?? fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((c) => c.put(req, copy))
          }
          return res
        }).catch(() => new Response('', { status: 504 })),
      ),
    )
    return
  }

  // Live data: hands off — the query layer owns freshness and offline grace.
  if (url.pathname.startsWith('/api/')) return

  // App navigations: try the network (fresh HTML after a deploy), fall back to
  // the cached shell so an offline reboot still boots the board.
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('/')))
    return
  }

  // Static assets (hashed → immutable): cache-first, populate on miss. A failed
  // fetch falls back to cache, else a 504 — never let respondWith reject.
  e.respondWith(
    caches.match(req).then((hit) =>
      hit ?? fetch(req).then((res) => {
        if (res.ok) {
          const copy = res.clone()
          caches.open(CACHE).then((c) => c.put(req, copy))
        }
        return res
      }).catch(() => new Response('', { status: 504 })),
    ),
  )
})
`

export default defineConfig({
  // Stamp the build moment into the bundle so Réglages ▸ Debug can show "last
  // updated" — a proxy for the last push (CI builds + deploys on every push to
  // main). Evaluated once when the build starts; in dev it's the dev-server start.
  define: {
    __BUILD_TIME__: JSON.stringify(new Date().toISOString()),
  },
  plugins: [react(), serviceWorker()],
  build: {
    rollupOptions: {
      output: {
        // B-11 (bmad/10) — pull the framework + i18n out of the eager entry into
        // their own named chunks: react/-dom/-router-dom rarely change build to
        // build so they cache across deploys instead of re-downloading inside a
        // renamed index-*.js every time app code changes; i18n.ts (the FR dict —
        // EN lazy-loads separately, see src/i18n.ts) is sizeable and cache-worthy
        // on its own. Everything else keeps Rollup's default automatic chunking.
        manualChunks: (id) => {
          if (id.includes('node_modules')) {
            if (/[\\/](react|react-dom|react-router|react-router-dom)[\\/]/.test(id)) return 'react-vendor'
            return undefined
          }
          if (id.endsWith('/src/i18n.ts')) return 'i18n'
          return undefined
        },
      },
    },
  },
  server: {
    // Pre-transform the lazy route modules at dev-server start. The app code-splits
    // ~40 pages via React.lazy; the FIRST hit on each cold-compiles in Vite, and
    // under the e2e suite's parallel workers that cold-compile can stall a
    // concurrent navigation → "failed to fetch dynamically imported module" /
    // ERR_CONNECTION_REFUSED flakes mid-run. Warming the page modules at boot races
    // them transformed before the tests hit them (non-blocking for server-ready;
    // also makes interactive first-navigation snappier). Pages pull their own
    // imports, so listing the route entries covers the split boundaries.
    warmup: {
      clientFiles: ['./src/main.tsx', './src/pages/**/*.tsx'],
    },
    proxy: {
      // Defaults to the local wrangler instance. Override with BABILLARD_API_PROXY
      // to point the frontend dev loop at a deployed Worker (e.g. real-data e2e
      // against prod) — changeOrigin so the Worker sees its own Host; the host-only
      // session cookies then land on 127.0.0.1 so login persists across the proxy.
      '/api': {
        target: process.env.BABILLARD_API_PROXY || 'http://127.0.0.1:8787',
        changeOrigin: true,
        secure: true,
      },
    },
  },
})
