// Every id-shaped field name a handler reads from a body or a query string — the
// names the isolation sweep (worker/isolation.d1.test.ts) fills with ANOTHER
// household's ids. Over-inclusion is harmless (an unread field is ignored); a MISSING
// name is a door the sweep never knocks on, which is why functions/test/idFields.test.ts
// greps the handlers and fails the build when one reads a name that is not here.
export const ID_FIELDS: readonly string[] = [
  'id',
  'aId',
  'bId',
  'behindMemberId',
  'bringTemplateId',
  'businessId',
  'carId',
  'carnetId',
  'choreId',
  'contactId',
  'cookMemberId',
  'deviceId',
  'eventId',
  'flyerId',
  'fromTripId',
  'groupId',
  'guestId',
  'habitId',
  'holderId',
  'linkId',
  'listId',
  'locationId',
  'lowId',
  'mealId',
  'memberId',
  'merchantId',
  'pairingId',
  'parentId',
  'personAId',
  'personBId',
  'personId',
  'planId',
  'primaryCarId',
  'recipeId',
  'recipientId',
  'revokeId',
  'revokeShareById',
  'routineId',
  'rowId',
  'sharedId',
  'sharedTripId',
  'sourceMealId',
  'swatchId',
  'templateId',
  'tripId',
  'vetBusinessId',
]
