import { MMID } from './mocks'

// Every route a whole-app sweep walks: the hub tabs and their sections, the scenes, and
// the form scenes. Shared by console-clean.spec.ts (a silent console) and spacing.spec.ts
// (the gap owns the spacing), so a route added for one is walked by both.
export const ROUTES = [
  // Hub tabs and their sections.
  '/board',
  '/kitchen',
  '/kitchen?tab=pantry',
  '/kitchen?tab=recipes',
  '/kitchen?tab=history',
  '/liste',
  '/notes',
  '/notes?section=virements',
  '/maison',
  '/maison?section=family',
  '/maison?section=social',
  '/maison?section=business',
  '/maison?section=carnets',
  '/settings',
  '/settings?tab=board',
  '/settings?tab=kitchen',
  '/settings?tab=liste',
  '/settings?tab=notes',
  '/settings?tab=maison',
  '/settings?tab=systeme',
  // Scenes.
  '/liste/circulaires',
  '/liste/cashier',
  '/liste/quick',
  '/liste/deals/l1',
  '/liste/item/l1',
  `/kitchen/day/${MMID}`,
  '/kitchen/idees',
  '/kitchen/book',
  '/kitchen/recipe/rc1',
  '/kitchen/recipe/rc1/cook',
  '/cercle/person/c1',
  '/cercle/monde',
  '/cercle/import',
  '/jouer',
  '/routine/r1/run',
  '/drawings',
  '/search',
  '/board/departure',
  '/board/habitudes',
  '/voiture',
  '/courrier',
  '/family',
  '/welcome',
  '/handoff',
  // Form scenes — where a primitive that owns its own <form> (EditField) meets a host
  // that owns one too. EntityCombobox is a <div> on purpose; EditField has `as="div"`.
  '/routine/r1',
  '/routine/new',
  '/kitchen/recipe/new',
  '/kitchen/recipe/rc1/edit',
  '/event/new',
  '/chore/new',
  '/home-project/new',
  '/habitude/new',
  '/habitude/hb1/edit',
  '/virement/new',
  '/virement/plan/new',
  '/cercle/person/new',
  '/cercle/pet/new',
  '/cercle/family/new',
  '/voyage/new',
  '/liste-modele/tpl1',
]
